/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Editor find bar",
  "description": "Adds a find bar to find and jump to scripts, costumes and sounds next to the sounds tab. Use Ctrl+Left and Ctrl+Right in the code area to navigate to previous or next visited position after using the find bar.",
  "info": [
    {
      "text": "This addon was previously part of the \"developer tools\" addon but has moved here.",
      "id": "developer-tools"
    }
  ],
  "credits": [
    {
      "name": "griffpatch"
    },
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/thecolaber/"
    },
    {
      "name": "Mistium",
      "link": "https://mistium.com"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Enable regex search",
      "id": "enableRegex",
      "type": "boolean",
      "default": false
    },
    {
      "dynamic": true,
      "name": "Case sensitive search by default",
      "id": "caseSensitive",
      "type": "boolean",
      "default": false
    },
    {
      "dynamic": true,
      "name": "Search across all sprites",
      "id": "searchAllSprites",
      "type": "boolean",
      "default": false
    },
    {
      "dynamic": true,
      "name": "Show search context",
      "id": "showContext",
      "type": "boolean",
      "default": true
    },
    {
      "dynamic": true,
      "name": "Max search history entries",
      "id": "maxHistory",
      "type": "integer",
      "min": 5,
      "max": 50,
      "default": 20
    }
  ],
  "tags": [
    "recommended",
    "MistWarp"
  ],
  "enabledByDefault": true
};
export default manifest;
