/* generated by pull.js */
const manifest = {
    editorOnly: true,
    name: '性能预算告警',
    description: '监控积木数/克隆数/列表长度/变量数，超阈值弹窗告警',
    credits: [
        {name: 'RemixWarp', link: ''}
    ],
    userscripts: [
        {url: 'userscript.js'}
    ],
    userstyles: [
        {url: 'userstyle.css'}
    ],
    settings: [
        {
            dynamic: true,
            name: '启用性能预算告警',
            id: 'enableBudgetAlert',
            type: 'boolean',
            default: true
        },
        {
            dynamic: true,
            name: '最大积木数',
            id: 'maxBlocks',
            type: 'integer',
            min: 100,
            max: 5000,
            default: 3000
        },
        {
            dynamic: true,
            name: '最大克隆数',
            id: 'maxClones',
            type: 'integer',
            min: 50,
            max: 300,
            default: 250
        },
        {
            dynamic: true,
            name: '最大列表项总数',
            id: 'maxListItems',
            type: 'integer',
            min: 1000,
            max: 50000,
            default: 10000
        },
        {
            dynamic: true,
            name: '最大变量数',
            id: 'maxVariables',
            type: 'integer',
            min: 100,
            max: 2000,
            default: 500
        },
        {
            dynamic: true,
            name: '检查间隔（毫秒）',
            id: 'checkInterval',
            type: 'integer',
            min: 500,
            max: 10000,
            default: 2000
        },
        {
            dynamic: true,
            name: '仅运行时检查',
            id: 'onlyWhenRunning',
            type: 'boolean',
            default: true
        }
    ],
    info: [
        {
            text: '超出阈值时在右下角显示 Toast 告警。支持在设置中自定义各项阈值。',
            id: 'pb-usage'
        }
    ],
    tags: ['editor', 'analysis', 'remixwarp', 'performance', 'budget', 'new'],
    enabledByDefault: true
};
export default manifest;