/* generated by pull.js */
const manifest = {
    editorOnly: true,
    name: 'workspace-tabs/name',
    description: 'workspace-tabs/description',
    tags: ['editor', 'workflow', 'MistWarp'],
    credits: [
        {
            name: 'Mistium',
            link: 'https://mistium.com'
        }
    ],
    dynamicDisable: true,
    userscripts: [
        {
            url: 'userscript.js'
        }
    ],
    userstyles: [
        {
            url: 'style.css'
        }
    ],
    enabledByDefault: true,
    settings: [
        {
            name: 'Maximum number of bookmarks',
            id: 'maxTabs',
            type: 'integer',
            min: 1,
            max: 100,
            default: 20
        },
        {
            name: 'Show bookmark numbers',
            id: 'showNumbers',
            type: 'boolean',
            default: true
        },
        {
            name: 'Enable categories',
            id: 'enableCategories',
            type: 'boolean',
            default: true
        },
        {
            name: 'Show search bar',
            id: 'showSearch',
            type: 'boolean',
            default: true
        },
        {
            name: 'Auto-backup bookmarks',
            id: 'autoBackup',
            type: 'boolean',
            default: true
        }
    ]
};
export default manifest;
