/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "隐藏菜单栏",
  "description": "隐藏编辑器顶部的菜单栏，增加工作区空间",
  "tags": ["new",'theme'],
  "credits": [
    {
      "name": "KOSHINO",
      "link": "https://github.com/KOSHINOawa"
    }
  ],
  "enabledByDefault": false,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ]
};
export default manifest;
