/* generated by pull.js */
const manifest = {
    editorOnly: true,
    name: '迷你地图',
    description: '在脚本编辑区右上角显示脚本缩略图导航，点击或拖动可快速定位到脚本的指定区域。',
    credits: [
        {name: '笑小朗', link: ''}
    ],
    userscripts: [
        {url: 'userscript.js'}
    ],
    userstyles: [
        {url: 'style.css'}
    ],
    settings: [
        {
            dynamic: true,
            name: '启用 Mini Map',
            id: 'enable_minimap',
            type: 'boolean',
            default: true
        },
        {
            dynamic: true,
            name: '缩略图宽度（像素）',
            id: 'width',
            type: 'integer',
            min: 80,
            max: 300,
            default: 140
        },
        {
            dynamic: true,
            name: '缩略图高度（像素）',
            id: 'height',
            type: 'integer',
            min: 60,
            max: 240,
            default: 120
        }
    ],
    info: [
        {
            text: '在脚本编辑区右上角显示缩略图。点击或拖动缩略图可快速定位脚本区域。',
            id: 'minimap-usage'
        }
    ],
    tags: ['editor', 'navigation', 'new'],
    enabledByDefault: true
};
export default manifest;
