/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Tab Styles",
  "description": "Change the appearance of the editor tabs to look like other mods.",
  "tags": ["editor", "MistWarp", "theme"],
  "credits": [
    {
        "name": "Mistium",
        "url": "https://mistium.com"
    },
    {
        "name": "RyaninCn11",
        "url": "https://github.com/RyaninCn11"
    },
    {
        "name": "笑小朗",
        "url": "https://github.com/xiaolanglang"
    }
  ],
  "dynamicDisable": true,
  "userstyles": [
    {
      "url": "bilup.css",
      "if": {
        "settings": {
          "tab_style": "bilup"
        }
      }
    },
    {
      "url": "turbowarp.css",
      "if": {
        "settings": {
          "tab_style": "turbowarp"
        }
      }
    },
    {
      "url": "scratchbox.css",
      "if": {
        "settings": {
          "tab_style": "scratchbox"
        }
      }
    },
    {
      "url": "remixwarp.css",
      "if": {
        "settings": {
          "tab_style": "remixwarp"
        }
      }
    },
    {
      "url": "icon-only.css",
      "if": {
        "settings": {
          "looks": "icon-only"
        }
      }
    },
    {
      "url": "text-only.css",
      "if": {
        "settings": {
          "looks": "text-only"
        }
      }
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Tab style",
      "id": "tab_style",
      "type": "select",
      "potentialValues": [
        {
            "name": "Bilup",
            "id": "bilup"
        },
        {
            "name": "TurboWarp",
            "id": "turbowarp"
        },
        {
            "name": "ScratchBox",
            "id": "scratchbox"
        },
        {
            "name": "RemixWarp",
            "id": "remixwarp"
        }
      ],
      "default": "Bilup"
    },
    {
      "dynamic": true,
      "name": "Looks",
      "id": "looks",
      "type": "select",
      "potentialValues": [
        {
            "name": "Default",
            "id": "default"
        },
        {
            "name": "Icon Only",
            "id": "icon-only"
        },
        {
            "name": "Text Only",
            "id": "text-only"
        }
      ],
      "default": "Default"
    }
  ],
  "enabledByDefault": false
};
export default manifest;
