/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Calculator",
  "description": "Adds a floating calculator window that you can use for quick math calculations while working on your projects. Features basic arithmetic operations, memory functions, and a clean, modern interface.",
  "credits": [
    {
        "name": "Mistium",
        "url": "https://mistium.com"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Show calculator button in menu",
      "id": "show_button",
      "type": "boolean",
      "default": true
    },
    {
      "dynamic": true,
      "name": "Remember window position",
      "id": "remember_position",
      "type": "boolean",
      "default": true
    }
  ],
  "tags": [
    "recommended",
    "new",
    "MistWarp"
  ],
  "enabledByDefault": false
};
export default manifest;
