/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./style.css";
import _asset from "!url-loader!./icons/calculator.svg";

export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "icons/calculator.svg": _asset,
};