/* generated by pull.js */
const manifest = {
    editorOnly: true,
    name: '项目大纲面板',
    description: '左侧树形展示角色/造型/声音/脚本/变量/广播，支持搜索与跳转',
    credits: [{name: 'RemixWarp', link: ''}],
    userscripts: [{url: 'userscript.js'}],
    userstyles: [{url: 'userstyle.css'}],
    settings: [
        {dynamic: true, name: '启用大纲面板', id: 'enableOutline', type: 'boolean', default: true},
        {dynamic: true, name: '自动展开当前角色', id: 'autoExpandCurrent', type: 'boolean', default: true}
    ],
    info: [{text: '编辑器左侧显示树形大纲，点击节点跳转到对应脚本/资源。', id: 'po-usage'}],
    tags: ['editor', 'navigation', 'remixwarp', 'outline', 'new'],
    enabledByDefault: true
};
export default manifest;