/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Resize selected item",
  "description": "Adds a button to the paint editor to resize selected items with precise width, height, and position values.",
  "credits": [
    {
      "name": "DL_Grass",
      "link": 'https://github.com/DLGrass/'
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "tags": ["new","recommended"],
  "dynamicDisable": true,
  "enabledByDefault": true
};
export default manifest;