/* generated by pull.js */
const manifest = {
  "name": "自制积木改函数",
  "description": "将选取积木区的类别中的'自制积木'显示为'函数'",
  "credits": [
    {
      "name": "笑小朗"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "ui",
    "blocks"
  ],
  "enabledByDefault": false
};
export default manifest;
