/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Cat blocks extended",
  "description": "Get April Fools' Day features that weren't released in RemixWarp editor for April Fools' Day 2026.",
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    },
    {
      "name": "GarboMuffin"
    },
    {
      "name": "笑小朗"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "info": [
    {
      "type": "notice",
      "text": "该插件为猫积木的扩展插件，包含猫积木插件，切勿不要同时开启猫积木插件与该插件。",
      "id": "watch"
    }
  ],
  "tags": [
    "theme",
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
