/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "clones/@name",
  "description": "clones/@description",
  "credits": [
    {
      "name": "Jeffalo"
    },
    {
      "name": "OregSam",
      "link": "https://scratch.mit.edu/users/simiagain/"
    },
    {
      "name": "DNin01"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "id": "projectpage",
      "name": "clones/@settings-name-projectpage",
      "default": false,
      "type": "boolean"
    },
    {
      "dynamic": true,
      "id": "showicononly",
      "name": "clones/@settings-name-showicononly",
      "default": false,
      "type": "boolean"
    }
  ],
  "tags": [
    "recommended"
  ],
  "enabledByDefault": false
};
export default manifest;
