/* generated by pull.js */
const manifest = {
    editorOnly: true,
    name: '事件追踪时序图',
    description: '记录广播/帽子积木触发时序，生成可视化时序图',
    credits: [{name: 'RemixWarp', link: ''}],
    userscripts: [{url: 'userscript.js'}],
    userstyles: [{url: 'userstyle.css'}],
    settings: [
        {dynamic: true, name: '启用事件追踪', id: 'enableTracing', type: 'boolean', default: true},
        {dynamic: true, name: '最大记录事件数', id: 'maxEvents', type: 'integer', min: 100, max: 5000, default: 500}
    ],
    info: [{text: '工具菜单 → 事件追踪 打开面板，项目运行时自动记录广播/触发时序。', id: 'et-usage'}],
    tags: ['editor', 'analysis', 'remixwarp', 'debug', 'new'],
    enabledByDefault: true
};
export default manifest;