/* generated by pull.js */
const manifest = {
  "name": "Terminal",
  "description": "Adds a button to open a standalone terminal window with xterm.js.",
  "credits": [
    {
      "name": "Cyberexplorer",
      "link": "https://github.com/LanwyWriteXU"
    }
  ],
  "tags": [
    "new",
    "recommended"
  ],
  "enabledByDefault": false,
  "userstyles": [
    {
      "url": "terminal.css"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true
};
export default manifest;