/* generated by pull.js */
const manifest = {
  "name": "终端",
  "description": "添加一个按钮以打开带有 xterm.js 的独立终端窗口",
  "credits": [
    {
      "name": "Cyberexplorer",
      "link": "https://github.com/LanwyWriteXU"
    }
  ],
  "tags": [
    "new",
    "recommended"
  ],
  "enabledByDefault": false,
  "userstyles": [
    {
      "url": "terminal.css"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true
};
export default manifest;