/* generated by pull.js */
const manifest = {
    editorOnly: true,
    name: '中文code注释编程',
    description: '在注释框中第一行写入 #cn.code 后，每写一行文本都会自动搜索并插入最匹配的积木，所有积木自动连接成链。',
    tags: [
        'recommended'
    ],
    enabledByDefault: true,
    userscripts: [
        {
            url: 'userscript.js'
        }
    ],
    info: [
        {
            text: '在任意积木或工作区注释的第一行写入 #cn.code 即可启用。之后每行文本都会被搜索并自动插入最匹配的积木，按回车切换到下一行时自动插入。',
            id: 'cn-code-usage'
        }
    ]
};
export default manifest;
