/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "中文 code（生成中文code）",
  "description": "为积木右键添加“生成中文code”选项，将选中脚本转换为中文注释/复制到剪贴板。",
  "tags": ["context-menu", "i18n"],
  "credits": [
    {
      "name": "TurboWarp"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "enabledByDefault": true
};
export default manifest;
