/* generated by pull.js */
import _js from "./hat.js";
import _js_snow from "./snowflakes.js";
import _js_projectloader from "./default-project-loader.js";
import _js_lights from "./lights.js";
import _css from "!css-loader!./userstyle.css";
export const resources = {
  "hat.js": _js,
  "snowflakes.js": _js_snow,
  "default-project-loader.js": _js_projectloader,
  "lights.js": _js_lights,
  "userstyle.css": _css,
};
