/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./style.css";
import _icon from "!url-loader!./autosave-icon.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "autosave-icon.svg": _icon,
};
