/* generated by pull.js */
const manifest = {
    editorOnly: true,
    name: '快捷键速查表',
    description: '按 ? 键唤出可搜索的快捷键速查表面板，按分类浏览、模糊搜索快捷键与功能。',
    credits: [
        {name: 'RemixWarp', link: ''}
    ],
    userscripts: [
        {url: 'userscript.js'}
    ],
    userstyles: [],
    settings: [
        {
            dynamic: true,
            name: '启用快捷键速查表',
            id: 'enable_cheatsheet',
            type: 'boolean',
            default: true
        },
        {
            dynamic: true,
            name: '唤起按键',
            id: 'trigger_key',
            type: 'select',
            default: '?',
            potentialValues: [
                {id: '?', name: '? (问号)'},
                {id: '/', name: '/ (斜杠)'},
                {id: 'F1', name: 'F1'}
            ]
        }
    ],
    info: [
        {
            text: '默认按 ? 键唤出速查表；在输入框中输入不会触发。可在设置中改为 / 或 F1。',
            id: 'keymap-cheatsheet-usage'
        }
    ],
    tags: ['editor', 'keymap'],
    enabledByDefault: true
};
export default manifest;
