/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "项目大小显示",
  "description": "在角色栏底部显示作品大小、代码数量和选中角色/舞台的大小。",
  "tags": ["editor", "new", "bilup"],
  "credits": [
    {
      "name": "DL_Grass",
      "link": 'https://github.com/DLGrass/'
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "enabledByDefault": false
};
export default manifest;
