/* generated by pull.js */
const manifest = {
    editorOnly: true,
    name: '性能剖析报告',
    description: '30秒性能剖析：热点积木、内存增长、线程阻塞、克隆统计',
    credits: [
        {name: 'RemixWarp', link: ''}
    ],
    userscripts: [
        {url: 'userscript.js'}
    ],
    userstyles: [
        {url: 'userstyle.css'}
    ],
    settings: [
        {
            dynamic: true,
            name: '剖析时长（秒）',
            id: 'profileDuration',
            type: 'integer',
            min: 5,
            max: 300,
            default: 30
        },
        {
            dynamic: true,
            name: '采样间隔（毫秒）',
            id: 'sampleInterval',
            type: 'integer',
            min: 50,
            max: 1000,
            default: 100
        },
        {
            dynamic: true,
            name: '热点积木显示上限',
            id: 'hotBlockLimit',
            type: 'integer',
            min: 10,
            max: 100,
            default: 30
        }
    ],
    info: [
        {
            text: '点击工具菜单 → 性能剖析 启动。完成后自动弹窗展示热点积木、线程阻塞、内存趋势。',
            id: 'pp-usage'
        }
    ],
    tags: ['editor', 'analysis', 'remixwarp', 'performance', 'new'],
    enabledByDefault: true
};
export default manifest;