/* generated by pull.js */
import _js from "./userscript.js";
import _jsoneditorCss from "!css-loader!jsoneditor/dist/jsoneditor.css";
import _css from "!css-loader!./style.css";
export const resources = {
  "userscript.js": _js,
  "jsoneditor.css": _jsoneditorCss,
  "style.css": _css,
};
