/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "我的积木增强",
  "description": "增强自定义积木的功能和灵活性",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "info": [
    {
      "type": "info",
      "text": "此插件将在创建项目时自动加载\"我的积木增强\"扩展",
      "id": "info"
    },
    {
      "type": "info",
      "text": "警告：它会加载新扩展，且无法在扩展管理器中移除。",
      "id": "warn"
    }
  ],
  "credits": [
    {
      "name": "SharkPool"
    },
    {
      "name": "CST1229"
    },
    {
      "name": "0znzw"
    },
    {
      "name": "KOSHINO",
      "link": "https://github.com/KOSHINOawa"
    }
  ],
  "dynamicDisable": true,
  "tags": ["new"]
};
export default manifest;
