/* generated by pull.js */
const manifest = {
    editorOnly: true,
    name: 'Project Health Dashboard',
    description: '项目健康度仪表盘：复杂度分析、代码规范检查、依赖图与综合健康度评分。',
    credits: [
        {name: 'RemixWarp', link: ''}
    ],
    userscripts: [
        {url: 'userscript.js'}
    ],
    userstyles: [
        {url: 'userstyle.css'}
    ],
    info: [
        {
            text: '通过工具菜单打开仪表盘，可查看项目的复杂度、规范问题与依赖关系。',
            id: 'phd-usage'
        }
    ],
    tags: ['editor', 'analysis', 'remixwarp'],
    enabledByDefault: true
};
export default manifest;
