/* generated by pull.js */
import _js from './userscript.js';
import _css from '!css-loader!./style.css';
import _asset from '!!raw-loader!./icons/camera.svg';

export const resources = {
    'userscript.js': _js,
    'style.css': _css,
    'icons/camera.svg': _asset
};

export const l10n = {
    en: {
        'screenshot-taken': 'Screenshot copied to clipboard!',
        'screenshot-error': 'Error taking screenshot',
        'screenshot-fallback': 'Screenshot downloaded (clipboard not supported)'
    }
};
