const shuffle = list => {
    for (let i = list.length - 1; i > 0; i--) {
        const random = Math.floor(Math.random() * (i + 1));
        const tmp = list[i];
        list[i] = list[random];
        list[random] = tmp;
    }
    return list;
};

const fromHardcoded = ({userID = '0', username}) => {
    const result = {
        image: `https://avatars.githubusercontent.com/u/${userID}`,
        text: username
    };
    if (username && userID !== '0') {
        result.href = `https://github.com/${username}/`;
    }
    return result;
};

// The lists below are in no particular order.

const contributors = [
    {
        userID: '67349469',
        username: 'TurboWarp'
    },
    {
        userID: '175630084',
        username: 'MistWarp'
    },
    {
        userID: '222322998',
        username: 'xiao-xiao-lang'
    },
    {
        userID: '148440803',
        username: 'RyaninCn11'
    }
].map(fromHardcoded);

const addonDevelopers = [
    {
        userID: '67349469',
        username: 'TurboWarp'
    },
    {
        userID: '175630084',
        username: 'MistWarp'
    },
    {
        userID: '222322998',
        username: 'xiao-xiao-lang'
    },
    {
        userID: '148440803',
        username: 'RyaninCn11'
    }

].map(fromHardcoded);

// generated by TurboWarp/extensions/scripts/get-credits-for-gui.js
// const extensionDevelopers = [

// ].map(fromHardcoded);

const docs = [
    {
        userID: '67349469',
        username: 'TurboWarp'
    },
    {
        userID: '175630084',
        username: 'MistWarp'
    },
    {
        userID: '222322998',
        username: 'xiao-xiao-lang'
    },
    {
        userID: '148440803',
        username: 'RyaninCn11'
    }
].map(fromHardcoded);

const translators = [
    {
        userID: '67349469',
        username: 'TurboWarp'
    },
    {
        userID: '175630084',
        username: 'MistWarp'
    },
    {
        userID: '222322998',
        username: 'xiao-xiao-lang'
    },
    {
        userID: '148440803',
        username: 'RyaninCn11'
    }
].map(fromHardcoded);

export default {
    contributors: shuffle(contributors),
    addonDevelopers: shuffle(addonDevelopers),
    // extensionDevelopers: shuffle(extensionDevelopers),
    docs: shuffle(docs),
    translators: shuffle(translators)
};
