// geng 梗体中文翻译（由 generated-translations.json 恢复生成）
module.exports = {
  "rotur.bilupShop.search.tooltip": "按关键词搜索商品（淘货）。",
  "rotur.bilupShop.order.text": "下单 %1 数量 %2（冲！）",
  "rotur.bilupShop.order.tooltip": "为指定商品创建订单（冲！）。",
  "rotur.bilupShop.orderStatus.text": "订单状态 %1（物流查询）",
  "rotur.bilupShop.orderStatus.tooltip": "获取指定订单的状态（物流查询）。",
  "rotur.bilupShop.orders.text": "我的订单（购物车记录）",
  "rotur.bilupShop.orders.tooltip": "获取当前用户的订单列表（剁手记录）。",
  "rotur.bilupShop.cancelOrder.text": "取消订单 %1（退款）",
  "rotur.bilupShop.cancelOrder.tooltip": "取消指定订单（反悔了）。",
  "rotur.bilupGroups.name": "Bilup 群组（拉帮结派）",
  "rotur.bilupGroups.description": "创建和管理群组，与成员协作（拉帮结派）。",
  "rotur.bilupGroups.docs": "Bilup 群组扩展文档（群聊说明书）",
  "rotur.bilupGroups.credits": "由 Bilup 团队提供（官方出品）",
  "rotur.bilupGroups.create.text": "创建群组 %1（建群）",
  "rotur.bilupGroups.create.tooltip": "使用指定名称创建一个新群组（建群）。",
  "rotur.bilupGroups.info.text": "群组信息 %1（群资料）",
  "rotur.bilupGroups.info.tooltip": "获取指定群组的详细信息（群资料）。",
  "rotur.bilupGroups.members.text": "群组成员 %1（群友）",
  "rotur.bilupGroups.members.tooltip": "获取指定群组的成员列表（群友）。",
  "rotur.bilupGroups.addMember.text": "添加成员 %1 至 %2（拉人进群）",
  "rotur.bilupGroups.addMember.tooltip": "将用户添加为群组成员（拉人进群）。",
  "rotur.bilupGroups.removeMember.text": "移除成员 %1 自 %2（踢人）",
  "rotur.bilupGroups.removeMember.tooltip": "从群组中移除指定成员（踢人）。",
  "rotur.bilupGroups.post.text": "在群组 %1 发布 %2（群里喊话）",
  "rotur.bilupGroups.post.tooltip": "在指定群组发布一条消息（群里喊话）。",
  "rotur.bilupGroups.messages.text": "群组消息 %1（群聊记录）",
  "rotur.bilupGroups.messages.tooltip": "获取指定群组的消息记录（群聊记录）。",
  "rotur.bilupGroups.delete.text": "删除群组 %1（解散群）",
  "rotur.bilupGroups.delete.tooltip": "删除指定群组（散伙）。",
  "rotur.bilupFiles.name": "Bilup 文件（网盘）",
  "rotur.bilupFiles.description": "上传、下载并管理你的文件资源（网盘）。",
  "rotur.bilupFiles.docs": "Bilup 文件扩展文档（网盘说明书）",
  "rotur.bilupFiles.credits": "由 Bilup 团队提供（官方出品）",
  "rotur.bilupFiles.list.text": "文件列表（网盘列表）",
  "rotur.bilupFiles.list.tooltip": "获取当前用户的文件列表（网盘列表）。",
  "rotur.bilupFiles.upload.text": "上传文件 %1 名为 %2（传文件）",
  "rotur.bilupFiles.upload.tooltip": "将文件上传到 Bilup 存储（传文件）。",
  "rotur.bilupFiles.downloadUrl.text": "下载链接 %1（下载地址）",
  "rotur.bilupFiles.downloadUrl.tooltip": "获取指定文件的下载链接（下载地址）。",
  "rotur.bilupFiles.delete.text": "删除文件 %1（删文件）",
  "rotur.bilupFiles.delete.tooltip": "自 Bilup 存储删除指定文件（删文件）。",
  "rotur.bilupFiles.rename.text": "重命名文件 %1 为 %2（改名）",
  "rotur.bilupFiles.rename.tooltip": "重命名指定文件（改名）。",
  "rotur.bilupFiles.quota.text": "存储配额（容量额度）",
  "rotur.bilupFiles.quota.tooltip": "获取当前用户的存储配额信息（容量还有多少）。",
  "rotur.bilupFiles.share.text": "分享文件 %1 给 %2（分享给）",
  "rotur.bilupFiles.share.tooltip": "将指定文件分享给另一位用户（分享给）。",
  "rotur.bilupFiles.sharedWithMe.text": "分享给我的文件（别人分享的）",
  "rotur.bilupFiles.sharedWithMe.tooltip": "获取其他用户分享给当前用户的文件列表（别人分享的）。",
  "tw.virtualKeyboard": "虚拟键盘（屏幕键盘）",
  "tw.settingsModal.searchPlaceholder": "搜设置...",
  "tw.settingsModal.cloud": "云服务（云端）",
  "tw.settingsModal.cloudVariableServer": "云变量服务器（云服务器）",
  "tw.settingsModal.cloudVariableServerHelp": "修改云变量用的服务器。URL 必须以 ws:// 或 wss:// 开头。",
  "mw.settings.groupGeneral": "常规（基础）",
  "mw.settings.groupAppearance": "外观（长相）",
  "mw.settings.layout": "布局（排版）",
  "mw.settings.editor": "编辑器（编辑区）",
  "mw.settings.styles": "样式（风格）",
  "mw.settings.menuBar": "菜单栏（菜单条）",
  "mw.settings.groupTools": "工具（工具箱）",
  "mw.settings.versionControl": "版本控制（时光机）",
  "mw.settings.variableManager": "变量管理器（盒子管家）",
  "mw.settings.debugger": "调试器（抓虫器）",
  "mw.settings.groupAdvanced": "高级（进阶）",
  "tw.settingsModal.styles": "样式（风格）",
  "tw.settingsModal.menuBar": "菜单栏（菜单条）",
  "tw.settingsModal.debugger": "调试器（抓虫器）",
  "tw.settingsModal.versionControl": "版本控制（时光机）",
  "tw.settingsModal.variableManager": "变量管理器（盒子管家）",
  "tw.settingsModal.superRefactor": "超级重构（大改造）",
  "tw.settingsModal.superRefactorHelp": "启用超级重构功能，提供更强大的代码重构工具（大力出奇迹）。",
  "tw.settingsModal.multiWorkspaces": "多工作区（多开）",
  "tw.settingsModal.multiWorkspacesHelp": "允许多个工作区同时打开（一心多用）。",
  "tw.settingsModal.hatBlockCommentReminder": "帽子块注释提醒（帽砖备忘）",
  "tw.settingsModal.hatBlockCommentReminderHelp": "在帽子块上提醒添加注释（帽砖备忘提醒）。",
  "tw.settingsModal.hatReminderCheckInterval": "检查间隔（毫秒）（多久查一次）",
  "tw.settingsModal.hatReminderBlockThreshold": "积木阈值（砖头数红线）",
  "tw.settingsModal.hatReminderCommentText": "注释文本（备忘文字）",
  "tw.settingsModal.stage": "舞台（场子）",
  "tw.settingsModal.activityBar": "活动栏（侧边栏）",
  "tw.settingsModal.blockPalette": "积木区（砖头区）",
  "tw.settingsModal.interface": "界面（UI）",
  "tw.settingsModal.enablemobiletouchdrag": "启用移动端触摸拖动（手机拖拽）",
  "tw.settingsModal.enablemobiletouchdraghelp": "在移动设备上启用触摸拖动功能（指哪拖哪）。",
  "tw.settingsModal.enableautoupdatecheck": "启用自动更新检查（自动查更新）",
  "tw.settingsModal.enableautoupdatecheckhelp": "启动时自动检查更新（有新版本提醒你）。",
  "tw.settingsModal.enableblockcounter": "启用积木计数器（数砖头）",
  "tw.settingsModal.enableblockcounterhelp": "在编辑器中显示积木数量统计（数砖头）。",
  "tw.settingsModal.enabledynamicstagebackground": "启用动态舞台背景（动态背景）",
  "tw.settingsModal.enabledynamicstagebackgroundhelp": "启用动态舞台背景效果（会动的背景）。",
  "tw.settingsModal.enablestatusbar": "启用状态栏（状态条）",
  "tw.settingsModal.enablestatusbarhelp": "在编辑器底部显示状态栏（底部小字）。",
  "tw.settingsModal.enablecommandpalette": "启用命令面板（命令面板）",
  "tw.settingsModal.enablecommandpalettehelp": "于“工具”菜单中提供命令面板入口（快捷键 Ctrl+K），关闭后将无法启动命令面板。（关了就没法用）",
  "tw.settingsModal.defaultvariable": "默认变量（需刷新）（自动建盒）",
  "tw.settingsModal.defaultvariablehelp": "开启后，新项目舞台上会自动创建下方配置的默认变量（自动建盒）；关闭则不创建任何默认变量。修改后需刷新编辑器，仅对新建项目生效。",
  "tw.settingsModal.defaultvariablename": "变量名称（盒子名）",
  "tw.settingsModal.defaultvariablenameplaceholder": "我的变量（我的盒子）",
  "tw.settingsModal.defaultvariablevalue": "变量值（盒子内容）",
  "tw.settingsModal.defaultvariablevalueplaceholder": "0",
  "tw.settingsModal.defaultvariableadd": "添加变量（加盒子）",
  "tw.settingsModal.defaultvariableremove": "删除该变量（扔盒子）",
  "tw.settingsModal.defaultvariablehint": "每个变量一行，可自定义变量名称与初始值（一行一个盒子）。",
  "tw.settingsModal.customdefaultsprite": "自定义默认角色（自定义初始崽崽）",
  "tw.settingsModal.customdefaultspritehelp": "设置新项目默认加载的角色（默认崽崽）。",
  "tw.settingsModal.customdefaultspriteupload": "上传角色（传崽崽）",
  "tw.settingsModal.customdefaultspritename": "角色名称（崽崽名）",
  "tw.settingsModal.customdefaultspritehint": "提示：上传一个角色文件用作新项目的默认角色（自带崽崽）。",
  "tw.settingsModal.customdefaultspriteuploaded": "已上传角色（崽崽已入）",
  "tw.settingsModal.customdefaultspriteerror": "上传失败，请重试（翻车了）。",
  "tw.settingsModal.customdefaultspritenameplaceholder": "输入角色名称（崽崽名）",
  "mw.settingsModal.windowAnimation": "窗口动画（动画效果）",
  "mw.settingsModal.windowAnimationHelp": "启用或禁用窗口动画效果（丝滑还是干脆）。",
  "mw.settingsModal.enableStageResize": "启用舞台缩放（拉舞台）",
  "mw.settingsModal.enableStageResizeHelp": "允许在编辑器中自由缩放舞台大小（随意拉舞台）。",
  "mw.settingsModal.vanillaPalette": "原版积木面板（原味积木区）",
  "mw.settingsModal.vanillaPaletteHelp": "用 Scratch 原版的积木面板样式（怀旧党狂喜）。",
  "mw.settingsModal.unclipPalette": "展开积木面板（摊开积木区）",
  "mw.settingsModal.unclipPaletteHelp": "展开积木面板，显示更多积木（视野全开）。",
  "mw.settings.activityBar": "活动栏（侧边栏）",
  "mw.stylePreview.code": "代码（代码区）",
  "mw.stylePreview.window": "窗口（窗）",
  "mw.stylePreview.preview": "预览（先看看）",
  "mw.settings.vc.authorName": "作者名称（大佬名）",
  "mw.settings.vc.authorNameHelp": "设置版本控制中使用的作者名称（存档留名）。",
  "mw.settings.vc.authorEmail": "作者邮箱（大佬邮箱）",
  "mw.settings.vc.authorEmailHelp": "设置版本控制中使用的作者邮箱（存档留邮箱）。",
  "mw.settings.vc.defaultBranch": "默认分支（默认岔路）",
  "mw.settings.vc.defaultBranchHelp": "设置版本控制的默认分支名称（默认岔路）。",
  "mw.settings.vc.autoCommit": "自动提交（自动存档）",
  "mw.settings.vc.autoCommitHelp": "启用自动提交功能，在保存时自动创建提交（自动存档）。",
  "mw.variableManager.defaultFilter": "默认筛选（默认过滤）",
  "mw.variableManager.defaultFilterHelp": "设置变量管理器的默认筛选模式（默认过滤）。",
  "mw.variableManager.all": "皆（全部）",
  "mw.variableManager.variables": "变（变量）",
  "mw.variableManager.lists": "列（列表）",
  "mw.variableManager.cloud": "云变量（云盒子）",
  "mw.variableManager.liveUpdate": "实时更新（即时刷新）",
  "mw.variableManager.liveUpdateHelp": "启用变量管理器的实时更新功能（实时刷新）。",
  "mw.variableManager.updateThrottle": "更新频率（毫秒）（刷新间隔）",
  "mw.variableManager.updateThrottleHelp": "设置变量管理器更新的最低间隔时间（刷新间隔）。",
  "mw.variableManager.variableMaxLength": "变量最大长度（盒子最长）",
  "mw.variableManager.variableMaxLengthHelp": "设置变量值的最大字符长度（盒子最长装多少）。",
  "mw.variableManager.listMaxLength": "列表最大长度（清单最长）",
  "mw.variableManager.listMaxLengthHelp": "设置列表的最大项目数量（清单最多几行）。",
  "gui.menuBar.bilupNova": "Bilup Nova（云AI）",
  "gui.menuBar.baiduAI": "百度AI（度娘）",
  "tw.menuBar.debuggerModal": "调器（调试器）",
  "gui.menuBar.achievements": "功（成就）",
  "gui.menuBar.extensionEditor": "扩编器（扩展编辑器）",
  "gui.menuBar.variousTools": "各种工具（工具箱）",
  "gui.menuBar.miniMap": "小地图（缩略图）",
  "gui.menuBar.projectHealth": "项目健康（体检报告）",
  "gui.menuBar.lintSystem": "代码检查（lint排雷）",
};
