// geng 梗体中文翻译（由 generated-translations.json 恢复生成）
module.exports = {
  "tw.settingsModal.customStageSizeHelp": "改Scratch的屏幕大小，默认480x360。比如改成640x360能整宽屏作品。但改完还能正常跑的作品少之又少（改完可能崩）。",
  "tw.settingsModal.dangerZone": "危险功能（作死区）",
  "tw.settingsModal.disableCompiler": "禁用编译器（关编译）",
  "tw.settingsModal.disableCompilerHelp": "禁用 {APP_NAME} 编译器。除非你在编辑作品想及时看到脚本效果，否则别开。",
  "tw.settingsModal.featured": "特色（招牌）",
  "tw.settingsModal.fps": "60 帧（自定义帧率，拉满）",
  "tw.settingsModal.fpsHelp": "每秒跑60次脚本而不是30次。开这个后大部分作品会不正常。真这样你就试试关了60帧用补帧。{customFramerate}。",
  "tw.settingsModal.fpsHelp.customFramerate": "点这儿设置30、60以外的帧率",
  "tw.settingsModal.help": "点这里看帮助",
  "tw.settingsModal.highQualityPen": "高清画笔（画质拉满）",
  "tw.settingsModal.highQualityPenHelp": "让画笔作品以更高分辨率渲染，还能避免编辑器里一些坐标精度丢失。可能影响性能，也不是所有作品都适合。",
  "tw.settingsModal.infiniteClones": "无限克隆（分身自由）",
  "tw.settingsModal.infiniteClonesHelp": "取消Scratch的300个克隆体上限（克隆自由）。",
  "tw.settingsModal.interpolation": "补帧（丝滑补帧）",
  "tw.settingsModal.interpolationHelp": "在角色运动里插帧让画面更丝滑。3D、光线追踪、纯画笔这类吃性能的作品别开，不然更卡还看不出效果（会卡成PPT）。",
  "tw.settingsModal.largeStageWarning": "不推荐自定义舞台大小！建议用同比例的低分辨率，让用户开全屏放大更合适。",
  "tw.settingsModal.removeFencing": "角色能穿出边缘",
  "tw.settingsModal.removeFencingHelp": "让角色能跑出屏幕、随便变大变小，屏幕外的触摸积木也有效。",
  "tw.settingsModal.removeLimits": "移除限制（解锁）",
  "tw.settingsModal.removeMiscLimits": "移除其他限制（全面解锁）",
  "tw.settingsModal.removeMiscLimitsHelp": "取消音效范围限制和画笔大小限制（解除封印）。",
  "tw.settingsModal.storeProjectOptions": "设置跟着作品走",
  "tw.settingsModal.storeProjectOptionsHelp": "把选好的设置存进作品文件，{APP_NAME} 加载作品时会自动应用。循环计时器和不用编译不会被保存。",
  "tw.settingsModal.title": "进阶设置",
  "tw.settingsModal.warpTimer": "循环计时器（防死循环）",
  "tw.settingsModal.warpTimerHelp": "让脚本检查自己是不是卡在长循环/无限循环里，卡住就低帧率跑，别死磕到循环结束。能解决大多数崩溃，但性能影响很大，所以默认只在编辑器里开。",
  "tw.settingsModal.caseSensitiveLists": "列表区分大小写（A不等于a）",
  "tw.settingsModal.caseSensitiveListsHelp": "让列表区分大小写，「a」和「A」算不同值。大多数项目不推荐，但重度用列表的项目能显著提速。",
  "tw.settingsModal.realLayerIndexes": "真实图层索引（图层自由）",
  "tw.settingsModal.realLayerIndexesHelp": "允许直接改图层索引来调整渲染顺序，图层数不再被可绘制对象数量卡死。",
  "tw.settingsModal.ae": "AstraEditor 设置（AE设置）",
  "tw.settingsModal.autodisplayreadme": "自动显示 README（开屏说明书）",
  "tw.settingsModal.autodisplayreadmeHelp": "项目打开后，如果有叫 'README' 的角色，就自动显示它里面的 README。",
  "tw.settingsModal.enablehtmlsupportreadme": "README里支持HTML",
  "tw.settingsModal.enablehtmlsupportreadmeHelp": "允许在 README 里用 HTML 标签。",
  "tw.settingsModal.skipcustomextwarn": "跳过自定义扩展警告（免弹窗）",
  "tw.settingsModal.skipcustomextwarnhelp": "项目加载时不用挨个同意自定义扩展，点一次'全部同意'就行。",
  "tw.settingsModal.enableextensionpreview": "加载扩展前预览（已弃用）",
  "tw.settingsModal.enableextensionpreviewhelp": "加载自定义扩展前先预览一下要加载的玩意儿。",
  "tw.settingsModal.enablevscodelayout": "VSCode 布局（需要刷新）",
  "tw.settingsModal.enablevscodelayouthelp": "把界面改成 VSCode 风格。",
  "tw.settingsModal.enablecoblielayout": "移动布局（需要刷新）",
  "tw.settingsModal.enablecoblielayouthelp": "调整舞台和角色区的位置，更适合移动端编辑。",
  "tw.soundEditorNotSupported": "浏览器不支持声音编辑器（换个浏览器吧）。",
  "tw.spriteSelectorItem.rename": "重命名（改名）",
  "tw.stageHeader.full": "完整大小（原尺寸）",
  "tw.stereo": "双声道（两边响）",
  "tw.stereoAlert": "编辑立体声音频会把它永久变单声道。",
  "tw.studioview.authorAttribution": "作者（大佬）：{author}",
  "tw.studioview.error": "加载下一页作品翻车了。",
  "tw.studioview.hoverText": "{title} 作者（大佬）：{author}",
  "tw.theme.gui.dark": "深色（黑化）",
  "tw.theme.gui.light": "浅色（白化）",
  "tw.theme.gui.midnight": "午夜（深夜模式）",
  "tw.tooLarge": "这音频太大了，传不上Scratch。",
  "tw.twExtension.description": "奇怪的新砖头，和Scratch不兼容，但能在Scratch用（怪东西）。",
  "tw.twExtension.name": "{APP_NAME} 积木（TW砖头）",
  "tw.unfavorite": "取消收藏（取关）",
  "tw.unknownPlatform.1": "这作品是另一个平台做的：",
  "tw.unknownPlatform.2": "没法保证和{APP_NAME}兼容。你可以头铁继续，但出了问题我们可能帮不上忙（风险自担）。",
  "tw.unknownPlatform.2.known": "这平台和{APP_NAME}基本兼容，编辑和运行应该没啥大问题。",
  "tw.unknownPlatform.continue": "懂了（知道了）",
  "tw.unknownPlatform.title": "平台信息（来路）",
  "tw.unshared.2": "想了解更多看 {link}",
  "tw.unshared.bug": "如果这作品其实发布了，请上报这个bug。",
  "tw.unshared.cache": "新作品发布几分钟内可能错误地显示这条消息（缓存问题）。",
  "tw.unshared2.1": "没发布的作品别人看不到。",
  "tw.usernameModal.help": "这个变量存在浏览器里。你跟含云变量的作品互动时，它可能会被记下来。",
  "tw.usernameModal.help2": "跟有效Scratch账号对不上的值一般会被云变量服务器拒绝。建议保持原样或者改成你的Scratch用户名。",
  "tw.usernameModal.mustChange": "抱歉，云变量服务器觉得你的用户名不安全。换一个吧，或者{resetIt}。",
  "tw.usernameModal.mustChange.resetIt": "重置（恢复出厂，推荐）",
  "tw.usernameModal.new": "用户名（马甲）：",
  "tw.usernameModal.reset": "重置（复原）",
  "tw.usernameModal.title": "更改用户名（换马甲）",
  "tw.usesCloudVariables": "这作品用了云变量。",
  "tw.usesCloudVariables2": "{APP_NAME} 的云变量和Scratch的云变量不是一回事。任何人都能把{changeTheirUsername}改成任何东西，小心冒名顶替（防伪提醒）。",
  "tw.usesCloudVariables2.change": "自己的用户名（我本人）",
  "tw.viewFeaturedProjects": "点这里看特色作品。",
  "tw.viewOnScratch": "去Scratch网站看这作品",
  "tw.webglModal.description": "你的浏览器{webGlLink}，但这网站靠它跑。试试更新浏览器和显卡驱动，或者重启设备（显卡不行就换）。",
  "tw.workspaceBookmarks.noMatching": "没匹配到书签（没找到）。",
  "tw.workspaceBookmarks.none": "无书签",
  "tw.workspaceBookmarks.add": "记下当前位置（加书签）",
  "tw.workspaceBookmarks.export": "导出",
  "tw.workspaceBookmarks.import": "导入",
  "tw.workspaceBookmarks.clearAll": "全清了（清空）",
  "tw.workspaceBookmarks.searchPlaceholder": "搜书签…",
  "tw.workspaceBookmarks.menuLabel": "书签（收藏位）",
  "tw.workspaceBookmarks.maxReached": "书签顶天了（{max} 个上限）",
  "tw.workspaceBookmarks.namePrompt": "书签名：",
  "tw.workspaceBookmarks.nameTitle": "书签名",
  "tw.workspaceBookmarks.categoryPrompt": "分类名（已有：{categories}）：",
  "tw.workspaceBookmarks.categoryTitle": "书签分类",
  "tw.workspaceBookmarks.errorTitle": "出错了",
  "tw.workspaceBookmarks.importTitle": "导入书签（读存档）",
  "tw.workspaceBookmarks.importErrorTitle": "导入失败（寄了）",
  "tw.workspaceBookmarks.clearTitle": "清空书签",
  "tw.workspaceBookmarks.defaultName": "书签 {number}（收藏点）",
  "tw.workspaceBookmarks.defaultCategory": "普通（默认分类）",
  "tw.workspaceBookmarks.editTooltip": "改书签",
  "tw.workspaceBookmarks.deleteTooltip": "删书签",
  "tw.workspaceBookmarks.importSuccess": "成功导入 {count} 个书签！",
  "tw.workspaceBookmarks.importFailed": "导入失败，文件格式不对（格式寄了）。",
  "tw.workspaceBookmarks.clearAllConfirm": "确定清空全部 {count} 个书签吗？没得后悔（删了就没咯）。",
  "tw.simpleDialog.ok": "欧了（确定）",
  "tw.simpleDialog.cancel": "算了（取消）",
  "mw.ok": "欧了（确定）",
  "mw.cancel": "算了（取消）",
  "mw.assets.title": "素材库（资源仓库）",
  "mw.assets.delete": "确定删了「{asset}」吗？用它搭的砖会集体罢工。",
  "mw.assets.newFolderPrompt": "文件夹名称（新窝名）",
  "mw.assets.add": "加文件",
  "mw.assets.newFolder": "新建文件夹（新窝）",
  "mw.assets.destination": "添加到 {folder}",
  "mw.assets.total": "{count} 个文件（共 {size}）",
  "mw.assets.none": "把文件拖进来、粘贴，或点「加文件」。砖没加载前素材不占资源（加载了才算数）。",
  "mw.assets.noPreview": "看不了预览",
  "mw.assets.noSelection": "先选个文件再看预览",
  "mw.assets.metaPath": "路径（路线）",
  "mw.assets.metaFormat": "格式（马甲）",
  "mw.assets.metaSize": "大小（体积）",
  "mw.assets.metaChecksum": "MD5 校验和（指纹）",
  "mw.assets.export": "导出（带走）",
  "mw.assets.deleteButton": "删除",
  "gui.customProcedures.blockColor": "砖头颜色",
  "mw.gitModal.branch": "分支（分岔）",
  "mw.gitModal.title": "Git 仓库（代码仓库）",
  "mw.gitModal.remotes": "远程仓库（远端）",
  "mw.gitModal.addRemote": "添加（整一个）",
  "mw.gitModal.addingRemote": "正在添加远程仓库…（连接远端）",
  "mw.gitModal.push": "推送（传上去）",
  "mw.gitModal.pushButton": "推送（传上去）",
  "mw.gitModal.pushingToRemote": "正在推送到远程仓库…（push中）",
  "mw.gitModal.authHelp": "注意：身份验证要 Git 服务器支持 CORS。GitHub 需要个人访问令牌（去生成个token）。",
  "mw.gitModal.disableCorsProxy": "禁用 CORS 代理（可能需要用来验证身份）",
  "mw.gitModal.refresh": "刷新（重刷）",
  "mw.gitModal.deleteRepo": "删仓库",
  "mw.gitModal.createBranch": "建分支",
  "mw.gitModal.deleteBranch": "删分支",
  "mw.gitModal.author": "作者（大佬）",
  "mw.gitModal.commit": "提交（存档）",
  "mw.gitModal.commitButton": "提交（存档）",
  "mw.gitModal.undoCommit": "撤销提交（读档）",
  "mw.gitModal.recent": "最近的提交（最近存档）",
  "mw.gitModal.restoreCommit": "还原（穿越回去）",
  "mw.gitModal.downloadCommit": "下载（扒下来）",
  "mw.gitModal.noCommits": "还没提交（空空的）",
  "mw.gitModal.newBranchPlaceholder": "新分支（新岔路）",
  "mw.gitModal.authorNamePlaceholder": "姓名（昵称）",
  "mw.gitModal.authorEmailPlaceholder": "user@example.com",
  "mw.gitModal.remoteNamePlaceholder": "远程仓库名（如：origin）",
  "mw.gitModal.remoteUrlPlaceholder": "https://github.com/user/repo.git",
  "mw.gitModal.usernamePlaceholder": "用户名（账号）",
  "mw.gitModal.tokenPlaceholder": "个人访问令牌 / 密码（暗号）",
  "mw.gitModal.selectRemotePlaceholder": "选远程仓库",
  "mw.gitModal.selectBranchPlaceholder": "选分支",
};
