// geng 梗体中文翻译（由 generated-translations.json 恢复生成）
module.exports = {
  "paint.sussyTool.shape.sun": "太阳（晒太阳）",
  "paint.sussyTool.shape.cloud": "云朵（棉花糖）",
  "paint.sussyTool.shape.lightningBolt": "闪电（皮卡丘）",
  "paint.sussyTool.shape.pentagonArrow": "五边形箭头（五角箭头）",
  "paint.sussyTool.shape.trapezoid": "梯形（梯子形）",
  "paint.sussyTool.shape.parallelogram": "平行四边形（斜边四边）",
  "paint.sussyTool.shape.kite": "风筝（纸鸢）",
  "paint.sussyTool.shape.check": "对勾（✓）",
  "paint.sussyTool.shape.cross": "乘号（✗）",
  "paint.sussyTool.shape.pin": "图钉（大头针）",
  "paint.sussyTool.shape.frown": "哭脸（呜呜呜）",
  "paint.sussyTool.shape.person": "人物（火柴人）",
  "paint.sussyTool.shape.star": "星星（✨）",
  "paint.sussyTool.shape.moon": "月亮（🌙）",
  "paint.sussyTool.shape.crescentMoon": "新月（弯弯月）",
  "paint.sussyTool.shape.musicNote": "连音符（🎵）",
  "paint.sussyTool.shape.musicNote2": "八分音符（♪）",
  "paint.sussyTool.shape.musicNote3": "高音谱号（🎼）",
  "paint.sussyTool.shape.sussy": "Sussy（这很可疑）",
  "paint.sussyTool.shape.fineman": "Fine Man（我没事）",
  "paint.sussyTool.shape.gear": "齿轮（⚙️）",
  "paint.sussyTool.shape.lightningBolt2": "闪电2（⚡）",
  "paint.sussyTool.shape.cloud2": "云朵2（☁️）",
  "paint.sussyTool.shape.pinPush": "图钉（📌）",
  "paint.sussyTool.shape.bookmark": "书签（🔖）",
  "paint.sussyTool.shape.note": "便签（📝）",
  "paint.sussyTool.shape.paper": "纸张（📄）",
  "paint.sussyTool.shape.eye": "眼睛（👀）",
  "bl.menu.bilme": "Bilme主题商店（主题商城）",
  "bl.menu.warptheme": "WarpTheme商店（主题商城）",
  "bl.bilme.title": "Bilme主题商店（皮肤商城）",
  "bl.bilme.searchPlaceholder": "搜主题...",
  "bl.bilme.sortBy": "排序（按啥排）",
  "bl.bilme.newest": "最新（新货）",
  "bl.bilme.likes": "最多点赞（赞最多）",
  "bl.bilme.name": "按名称（按名字）",
  "bl.bilme.allPlatforms": "所有平台（全平台）",
  "bl.bilme.RemixWarp": "RemixWarp",
  "bl.bilme.allColors": "所有颜色（全色系）",
  "bl.bilme.red": "红（中国红）",
  "bl.bilme.orange": "橙（橘里橘气）",
  "bl.bilme.yellow": "黄（阿黄）",
  "bl.bilme.green": "绿（原谅色）",
  "bl.bilme.blue": "蓝（yyds蓝）",
  "bl.bilme.purple": "紫（基佬紫）",
  "bl.bilme.login": "登录（上号）",
  "bl.bilme.logout": "登出（下线）",
  "bl.bilme.createTheme": "创建主题（整皮肤）",
  "bl.bilme.noThemes": "没找到主题（空空）",
  "bl.bilme.loading": "加载主题中...（读皮肤中）",
  "bl.bilme.error": "加载主题失败（寄了）",
  "bl.bilme.likesCount": "{count} 个赞",
  "bl.bilme.downloadsCount": "{count} 次下载",
  "bl.bilme.applyTheme": "应用（穿上）",
  "bl.bilme.openInBilme": "在 Bilme 中打开（去商店看）",
  "paint.sussyTool.shape.lock": "锁（🔒）",
  "paint.sussyTool.shape.lockOpened": "开锁（🔓）",
  "paint.sussyTool.shape.inbox": "收件箱（📥）",
  "paint.sussyTool.shape.speechBubble": "对话气泡（说话框）",
  "paint.sussyTool.shape.thinkingBubble": "思考气泡（想啥呢）",
  "paint.sussyTool.shape.shoutBubble": "喊叫气泡（大喊大叫）",
  "paint.sussyTool.shape.squareBubble": "方形气泡（方块框）",
  "paint.sussyTool.shape.codeblock": "代码块（积木块）",
  "paint.sussyTool.shape.codeblockHat": "帽子块（帽积木）",
  "paint.sussyTool.shape.codeblockEndCap": "末端块（收尾）",
  "paint.sussyTool.shape.codeblockReporter": "报告块（圆头）",
  "paint.sussyTool.shape.codeblockBoolean": "布尔块（六边形）",
  "tw.menuBar.bookmarkDefaultName": "书签 {number}（收藏点）",
  "tw.menuBar.bookmarkDefaultCategory": "常规（默认）",
  "gui.menuBar.undo": "撤（回退）",
  "gui.menuBar.redo": "复（重做）",
  "gui.collaboration.title": "实时协作（多人联机）",
  "gui.collaboration.alphaWarningLabel": "Alpha 警告（测试版预警）：",
  "gui.collaboration.alphaWarningMessage": "此功能还在早期开发阶段。你的项目可能会坏掉或出错。用了就后果自负。",
  "gui.collaboration.currentUsername": "你的用户名是（你的马甲）：{username}",
  "gui.collaboration.joinTitle": "加入现有房间（进房）",
  "gui.collaboration.roomId": "房间ID（房号）",
  "gui.collaboration.roomIdPlaceholder": "输入房间ID...（房号）",
  "gui.collaboration.joinRoom": "加入房间（进房）",
  "gui.collaboration.createTitle": "创建新房间（开黑房）",
  "gui.collaboration.createDescription": "生成新的房间ID开始协作。分享房间URL邀请他人。",
  "gui.collaboration.createRoom": "创建新房间（开房）",
  "gui.collaboration.connecting": "正在连接房间...（连房中）",
  "gui.collaboration.cancel": "算了（取消）",
  "gui.collaboration.connectedRoom": "房间（房号）：{roomId}",
  "gui.collaboration.status": "已连接 - {userCount} 人在线",
  "gui.collaboration.connectedUsers": "已连接用户（在线名单）",
  "gui.collaboration.host": "房主（群主）",
  "gui.collaboration.you": "你（本尊）",
  "gui.collaboration.kick": "踢出（踢人）",
  "gui.collaboration.pendingRequests": "待处理的加入请求 ({count})（求加入）",
  "gui.collaboration.approve": "批准（放行）",
  "gui.collaboration.deny": "拒绝（不让进）",
  "gui.collaboration.roomPrivacySettings": "房间隐私设置（房门锁）",
  "gui.collaboration.publicRoom": "公开房间（谁都能进）",
  "gui.collaboration.publicRoomDesc": "任何人都能加入，不用批准",
  "gui.collaboration.privateRoom": "私人房间（熟人局）",
  "gui.collaboration.privateRoomDesc": "用户必须申请批准才能加入",
  "gui.collaboration.makePublic": "设为公开（敞开大门）",
  "gui.collaboration.makePrivate": "设为私人（锁门）",
  "gui.collaboration.copyRoomUrl": "复制房间URL来分享",
  "gui.collaboration.leaveRoom": "离开房间（跑路）",
  "gui.collaboration.waitingApproval": "等待房主批准（等群主放行）",
  "gui.collaboration.pendingApprovalDescription": "你加入这个私人房间的申请已发给房主。等着吧。",
  "gui.collaboration.cancelRequest": "取消请求（撤了）",
  "gui.collaboration.userDisconnected": "{username} 掉线了",
  "gui.collaboration.hostLeft": "房主离开了协作房间。房间已关。",
  "gui.collaboration.disconnected": "已断开协作房间连接（掉线了）",
  "gui.collaboration.downloadFailed": "从房主下载项目失败（下载翻车）",
  "gui.collaboration.joinFailed": "加入房间失败（进不去）",
  "gui.collaboration.createFailed": "创建房间失败（开房失败）",
  "gui.collaboration.kickedFromRoom": "你被房主踢出了协作房间。",
  "gui.collaboration.approveFailed": "批准加入请求失败（没批成）",
  "gui.collaboration.denyFailed": "拒绝加入请求失败（没拒成）",
  "gui.collaboration.joinDenied": "你的加入请求被拒了",
  "gui.collaboration.changePrivacyFailed": "更改房间隐私设置失败（锁没换好）",
  "gui.collaboration.waitingForHost": "等待房主加载项目...（等房主读档）",
  "gui.collaboration.synchronizing": "正在与所有客户端同步...（全员同步中）",
  "gui.collaboration.settingsButtonTitle": "协作设置（联机设置）",
  "gui.collaboration.joinPrivacyNotice": "加入协作房间后，你的用户名和项目会和其他参与者共享。",
  "gui.collaboration.hostPrivacyNotice": "房主能看到房间里所有参与者的用户名和项目内容。",
  "gui.collaboration.settingsTitle": "连接设置（网络设置）",
  "gui.collaboration.closeSettingsTitle": "关闭设置（收起）",
  "gui.collaboration.peerServerConfig": "PeerJS 服务器配置（中转服务器）",
  "gui.collaboration.peerHost": "主机（服务器）",
  "gui.collaboration.peerHostPlaceholder": "输入主机地址...（服务器地址）",
  "gui.collaboration.peerPort": "端口（口子）",
  "gui.collaboration.peerPortPlaceholder": "输入端口号...（端口）",
  "gui.collaboration.peerKey": "密钥（暗号）",
  "gui.collaboration.peerKeyPlaceholder": "输入 API 密钥...（钥匙）",
  "gui.collaboration.peerPath": "路径（路线）",
  "gui.collaboration.peerPathPlaceholder": "输入路径...（路线）",
  "gui.collaboration.peerSecure": "安全连接 (HTTPS/WSS)（加密传输）",
  "gui.collaboration.cancelSettings": "算了（取消）",
  "gui.collaboration.saveSettings": "保存设置（存档）",
  "gui.collaboration.backupHostHint": "备用方案（MistWarp 协作服务器，备胎）:",
  "gui.collaboration.copyTooltip": "点一下复制",
  "gui.collaboration.copied": "已复制！（复制成功）",
  "gui.collaboration.chatHint": "协作时按 {shortcut} 开始聊天（喊话）",
  "tw.extensionLibrary.emptyIdle": "此扩展库暂无扩展（空空如也）。",
  "tw.collaboration.chatPlaceholder": "输入消息...（打几个字）",
  "bl.bilme.downloadTheme": "下载主题（扒下来）",
  "tw.menuBar.collaboration": "实时协作（多人联机）",
  "tw.securityBanner.title": "安全警告（小心）",
  "tw.securityBanner.line1": "TurboWarp 在所有版本的 Scratch 里发现了一个大漏洞。桌面应用里，打开恶意项目可能在你电脑上装勒索软件。",
  "tw.securityBanner.line2": "TurboWarp 两年前就报告给 Scratch 了，但还没修。最新版 TurboWarp 不受影响。更多详情见 {link}。",
  "tw.securityBanner.close": "阖（关掉）",
  "tw.menuBar.tutorial": "教程（新手村）",
  "tw.tutorialModal.title": "教程（新手村）",
  "tw.collaboration.error.connectionTimeout": "连接到房间 \"{roomId}\" 超时。房主可能不在线。",
  "tw.collaboration.error.hostUnavailable": "连不上房主。房间 \"{roomId}\" 可能不存在或房主离线了。",
  "tw.collaboration.error.iceConnectionFailed": "ICE 连接在 {attempts} 次尝试后失败。多半是网络问题。",
  "tw.collaboration.error.unknown": "连接失败（掉线）：{error}",
  "mw.menuBar.git": "Git 仓库（代码仓库）",
  "mw.menuBar.commandPalette": "命令面板（Ctrl+K）",
  "mw.panel.problems": "问题（排雷）",
};
