// geng 梗体中文翻译（由 generated-translations.json 恢复生成）
module.exports = {
  "mw.gitModal.error.commitMessageRequired": "提交信息总得写两句吧（不然存啥档）。",
  "mw.gitModal.error.cannotUndoWhileDetached": "分离状态下没法撤销提交。先切回某个分支再说。",
  "mw.gitModal.error.noPreviousCommit": "没有可撤销的提交（没档可回）",
  "mw.gitModal.error.branchNameRequired": "分支名不能空着",
  "mw.gitModal.error.selectDifferentBranch": "挑个不一样的分支才能合并",
  "mw.gitModal.error.remoteNameRequired": "远程仓库名不能空着",
  "mw.gitModal.error.remoteUrlRequired": "远程仓库 URL 不能空着",
  "mw.gitModal.error.selectPushRemote": "推送前先选个远程仓库",
  "mw.gitModal.error.selectPushBranch": "推送前先选个分支",
  "mw.gitModal.repo": "仓库（存档点）",
  "mw.gitModal.repo.notInitialized": "还没初始化仓库",
  "mw.gitModal.commitMessagePlaceholder": "写下提交信息…",
  "mw.gitModal.init": "初始化（起头）",
  "mw.gitModal.confirmDelete": "删除（扔了）",
  "mw.gitModal.deleteRepo.confirmMessage": "删除此 Git 仓库？\n\n这会从当前浏览器会话 / 本地存储里移除该仓库。\n想留提交历史的话，先保存项目，把 git.json 嵌进 SB3 文件里。",
  "mw.gitModal.deleteBranch.confirmMessage": "删除分支「{ref}」？\n\n这波操作没得撤销。",
  "mw.gitModal.busy": "正在处理…（干活中）",
  "mw.gitModal.refreshing": "正在刷新…（重刷中）",
  "mw.gitModal.init-ing": "正在初始化…（开箱中）",
  "mw.gitModal.committing": "正在提交…（存档中）",
  "mw.gitModal.undoingCommit": "正在撤销提交…（回档中）",
  "mw.gitModal.creatingBranch": "正在建分支…",
  "mw.gitModal.checkingOutBranch": "正在切分支…",
  "mw.gitModal.restoringCommit": "正在还原提交…（穿越中）",
  "mw.gitModal.preparingDownload": "正在准备下载…（打包中）",
  "mw.gitModal.deletingRepo": "正在删仓库…",
  "mw.gitModal.deletingBranch": "正在删分支…",
  "mw.gitModal.analyzingMerge": "正在分析合并…（算合体中）",
  "mw.gitModal.merging": "正在合并…（合体中）",
  "mw.git.computing": "计算文件状态中…（数文件）",
  "mw.git.staging": "暂存文件中…（登记中）",
  "mw.git.initializing": "初始化仓库中…（开箱中）",
  "mw.git.savingSnapshot": "保存项目快照中…（拍照中）",
  "mw.git.commit": "创建提交中…（存档中）",
  "mw.git.writingSnapshot": "写入 SB3 快照中…（写入中）",
  "mw.git.noFileSelected": "没选文件",
  "mw.git.initialCommit": "首次提交（开张大吉）",
  "mw.git.writeProject": "正在写入项目文件…（存盘）",
  "mw.git.writeScripts": "正在写入 {spriteName} 的脚本…（记录代码）",
  "mw.git.writeCostumes": "正在写入 {spriteName} 的造型…（登记换装）",
  "mw.git.writeSounds": "正在写入 {spriteName} 的声音…（收录音效）",
  "mw.git.writeMetadata": "正在写入 {spriteName} 的元数据…（填写档案）",
  "mw.git.rotur.signedOut": "用 Bilup 账户登录，就能在 git.bilup.org 建仓库，还能从 Bilup 直接推项目。",
  "mw.git.rotur.signIn": "用 Bilup 账户登录（上号）",
  "mw.git.rotur.heading": "你的仓库（你的地盘）",
  "mw.git.rotur.signedInAs": "已登录为 {username}。仓库在 {link}。",
  "mw.git.rotur.connectedTag": "已连上（对接完成）",
  "mw.git.rotur.connectedDesc": "这项目会推送和拉取这个仓库。",
  "mw.git.rotur.pushRepo": "把项目推到这仓库",
  "mw.git.rotur.openRepo": "在 git.bilup.org 打开（外部查看）",
  "mw.git.rotur.cloneRepo": "把这个仓库克隆成你的项目",
  "mw.git.rotur.deleteRepo": "删仓库",
  "mw.git.rotur.cloneConfirm": "这会替换你当前的项目。再点一次克隆才确认。",
  "mw.git.rotur.deleteConfirm": "这会永久删除 Bilup Git 上的仓库。再点一次删除才确认。",
  "mw.git.rotur.private": "私有仓库（私密小窝）",
  "mw.git.rotur.create": "建一个仓库",
  "mw.git.rotur.namePlaceholder": "仓库名称（存档点名）",
  "mw.git.rotur.descPlaceholder": "描述（选填，介绍下）",
  "mw.git.rotur.createButton": "创建（整一个）",
  "mw.git.rotur.privateCheckbox": "私有仓库（加密）",
  "mw.git.rotur.repoList": "仓库（列表）",
  "mw.git.rotur.reload": "重新加载仓库（重刷）",
  "mw.git.rotur.loading": "正在加载仓库…（读档中）",
  "mw.git.rotur.noRepos": "还没仓库。先在上面建一个，再把项目推过去。",
  "mw.git.rotur.pushHelp": "推送会把你提交的历史传上去。推送未初始化的项目会先本地建仓库并生成首次提交。",
  "mw.git.rotur.cloneOther": "克隆任意 Bilup Accounts 仓库（复制别人的存档）",
  "mw.git.rotur.cloneOtherButton": "克隆（复制粘贴）",
  "mw.git.rotur.cloneOtherHelp": "克隆别人的仓库会当成你的项目打开；推送到自己的仓库才能留档。",
  "mw.git.title": "版本控制（时光机）",
  "mw.git.nav.changes": "更改（动了啥）",
  "mw.git.nav.history": "历史（编年史）",
  "mw.git.nav.branches": "分支（分岔）",
  "mw.git.nav.diff": "差异（找不同）",
  "mw.git.nav.remote": "远程（远端）",
  "mw.git.nav.settings": "设置",
  "mw.git.nav.readme": "说明（README）",
  "mw.git.nav.rotur": "Bilup Git（云存档）",
  "mw.git.empty.description": "这项目还没开版本控制（没上户口）。",
  "mw.git.empty.init": "初始化仓库（上户口）",
  "mw.git.empty.or": "或者克隆一个现有的 fractch 项目",
  "mw.git.empty.clone": "克隆（复制粘贴）",
  "mw.git.empty.cloneConfirm": "克隆会替换当前项目。放弃未保存的更改并克隆？",
  "mw.git.empty.cloneAnyway": "照样克隆（头铁）",
  "mw.git.empty.cloneCancel": "算了（取消）",
  "mw.git.empty.cloneHint": "私有仓库用你的令牌（远程）和作者名称（设置）。",
  "mw.git.changes.heading": "工作区更改（没存档的改动）",
  "mw.git.changes.commit": "提交（存档）",
  "mw.git.changes.undo": "撤销上次提交（回档）",
  "mw.git.changes.placeholder": "描述你的更改…（说说改啥）",
  "mw.git.changes.none": "没有未提交的更改（干干净净）。",
  "mw.git.settings.danger": "危险区（作死区）",
  "mw.git.settings.deleteRepo": "删仓库",
  "mw.git.history.heading": "提交历史（档案室）",
  "mw.git.history.none": "暂无提交（没档案）。",
  "mw.git.history.files": "此提交里改过的文件",
  "mw.git.history.restore": "恢复此提交（穿越）",
  "mw.git.history.download": "下载为 .sb3（扒下来）",
  "mw.git.history.noFiles": "没有文件级别的更改可显示。（无改动）",
  "mw.git.branches.heading": "分支（分岔）",
  "mw.git.branches.current": "当前分支（现在的位）",
  "mw.git.branches.new": "建新分支",
  "mw.git.branches.create": "创建（整一个）",
  "mw.git.branches.currentTag": "当前（现在这个）",
  "mw.git.branches.merge": "合并（合体）",
  "mw.git.branches.preview": "预览（瞅瞅）",
  "mw.git.branches.conflictHelp": "每个文件选一方来解决冲突：",
  "mw.git.branches.ours": "我们的版本（我们赢）",
  "mw.git.branches.theirs": "他们的版本（他们赢）",
  "mw.git.branches.apply": "应用合并（就这样合）",
  "mw.git.branches.delete": "删分支",
  "mw.git.branches.mergeFrom": "从…合并",
  "mw.git.branches.resolveInEditor": "在编辑器里解决（手动调）",
  "mw.git.diff.heading": "差异（找不同）",
  "mw.git.diff.explain": "工作区 vs 上次提交。选文件看可读的 fractch 差异。",
  "mw.git.diff.none": "没有未提交的更改可比较。（全存了）",
  "mw.git.remote.heading": "远程仓库（远端）",
  "mw.git.remote.none": "还没远程仓库。在下面加一个来推送项目。",
  "mw.git.remote.add": "添加远程仓库（连远端）",
  "mw.git.remote.token": "Forgejo 访问令牌 (PAT)（钥匙）",
  "mw.git.remote.tokenHelp": "于 git.bilup.org → 设置 → 应用程序 → 生成新令牌处获取。Bilup Git API 调用需要此令牌。",
  "mw.git.remote.pushBranch": "推送分支（上传分支）",
  "mw.git.remote.push": "推送（传上去）",
  "mw.git.remote.pushHelp": "在远程建分支并设为上游（类似 git push -u）。",
  "mw.git.remote.remove": "删远程仓库",
  "mw.git.remote.noneOption": "无远程仓库（没连远端）",
  "mw.git.readme.heading": "项目说明（README）",
  "mw.git.readme.explain": "存成仓库里的 README.md。会随项目一起提交、克隆，并带进 .sb3 文件里。",
  "mw.git.readme.save": "保存 README",
  "mw.git.refresh": "刷新（重刷）",
  "mw.git.diff.computing": "正在算差异…",
  "mw.git.diff.empty": "选个文件看它改了啥。",
  "mw.git.diff.noChanges": "这文件没改动。",
  "mw.settings.general": "常规（基础）",
  "mw.settings.experimental": "实验性（整活区）",
  "mw.settingsModal.storeThemeInProject": "把主题存进作品",
  "mw.settingsModal.storeThemeInProjectHelp": "开启后，点「将设置存储到项目中」也会把当前的 {APP_NAME} 主题一起存进去，加载项目时自动应用。",
  "tw.addonSettings.title": "插件设置（外挂设置）",
  "tw.extensionManager.blocksColumn": "积木数（砖头数）",
  "tw.extensionManager.blocksUnit": "积木（块砖）",
  "tw.extensionManager.delete": "删除（扔了）",
  "tw.extensionManager.deleteExtension": "删扩展（卸外挂）",
  "tw.extensionManager.deleteSelected": "删除选中 ({count})（扔了）",
  "tw.extensionManager.dragHint": "拖动行可调整扩展顺序（排排站）",
  "tw.extensionManager.extensionColumn": "扩展（外挂）",
  "tw.extension.remixWarp.name": "TurboWarp 积木（TW砖头）",
  "tw.extension.rotur.name": "Bilup Accounts 账号（上号）",
  "tw.extension.rotur.description": "用 Bilup Accounts 登录（上号）并读取玩家身份（查户口）。",
  "tw.extension.roturEconomy.name": "Bilup Accounts 经济（钱包）",
  "tw.extension.roturEconomy.description": "积分、转账和每日奖励（数钱）。",
  "tw.extension.roturKeys.name": "Bilup Accounts 密钥（钥匙串）",
  "tw.extension.roturKeys.description": "购买、出售和查看 Bilup Accounts 密钥（倒腾钥匙）。",
  "tw.extension.roturStatus.name": "Bilup Accounts 状态（在线检测）",
  "tw.extension.roturStatus.description": "读取和设置 Bilup Accounts 状态与在线状态（查上没上线）。",
  "tw.extension.roturSocial.name": "Bilup Accounts 社交（混圈子）",
  "tw.extension.roturSocial.description": "于 Bilup Accounts 上发帖、关注和交友（混圈子）。",
  "tw.extension.roturShop.name": "Bilup Accounts 商店（剁手店）",
};
