// geng 梗体中文翻译（由 generated-translations.json 恢复生成）
module.exports = {
  "mw.info.usageParagraph2": "编辑器里的账号登录，和你查看“我的作品”、“通知”界面的两个登录机制是分开的，这在 Bilup 上没有，所以你得登录两遍（别惊讶，真·双登录）。",
  "mw.info.usageParagraph3": "其余使用可能没啥差别（就酱）。",
  "mw.share.progress.creatingRemix": "创建改编项目（魔改中）",
  "mw.share.progress.creatingProject": "正在创建项目（建档中）",
  "mw.share.progress.packagingProject": "正在打包项目（装箱中）",
  "mw.share.progress.uploadingProject": "正在上传项目（传作品中）",
  "mw.share.progress.processingOnServer": "正在服务器上处理（服务器狂转）",
  "mw.share.progress.uploadingPercent": "正在上传 {percent}%（传了{percent}%）",
  "achievements.welcomeTitle": "欢迎使用 RemixWarp（欢迎入坑）",
  "achievements.welcomeSubtitle": "选一下你的编辑器经验，决定默认开不开成就和新手教程。",
  "achievements.importConfig": "导入全部配置（读全设置）",
  "achievements.scratchBeginner": "Scratch小白（萌新）",
  "achievements.scratchBeginnerDesc": "自动开成就，显示新手教程",
  "achievements.turboWarpExpert": "TurboWarp大佬（老油条）",
  "achievements.turboWarpExpertDesc": "可在实验性设置里开成就，不显示新手教程",
  "achievements.selectDeviceTitle": "选你的设备",
  "achievements.selectDeviceSubtitle": "选你主要用的设备类型，我们好优化编辑器体验。",
  "achievements.mobileDevice": "移动端（手机党）",
  "achievements.mobileDeviceDesc": "自动开移动端布局和触屏模式",
  "achievements.pcDevice": "PC 端（电脑党）",
  "achievements.pcDeviceDesc": "用标准桌面版布局",
  "achievements.goBack": "返（回去）",
  "achievements.selectLayoutTitle": "选你的布局",
  "achievements.selectLayoutSubtitle": "选编辑器布局，和高级设置里的“选择布局”一个意思。",
  "achievements.vscodeLayout": "VS Code 布局（码农风格）",
  "achievements.vscodeLayoutDesc": "左侧活动栏 + 右侧多标签页工作区（码农经典布局）",
  "achievements.scratchLayout": "Scratch 布局（原版布局）",
  "achievements.scratchLayoutDesc": "经典 Scratch 界面布局（原版布局）",
  "tw.customExtensionGallery.title": "加载自定义扩展库（读自装外挂库）",
  "tw.customExtensionGallery.nameLabel": "扩展库名称（外挂库名）",
  "tw.customExtensionGallery.namePlaceholder": "我的扩展库（外挂库）",
  "tw.customExtensionGallery.urlLabel": "扩展库 URL（外挂库地址）",
  "tw.customExtensionGallery.urlPlaceholder": "https://example.com/extensions.json",
  "tw.customExtensionGallery.typeUrl": "URL（网址）",
  "tw.customExtensionGallery.typeFile": "文件（本地货）",
  "tw.customExtensionGallery.filePrompt": "选本地 JSON 文件：",
  "tw.customExtensionGallery.fileSelected": "已选文件：{fileName}",
  "tw.customExtensionGallery.hint": "指向一个 JSON 元数据文件，格式和内置扩展库一样：包含 extensions 数组的对象，或纯扩展对象数组。加载后，扩展库会出现在侧边栏并带自己的状态指示灯（有灯就是有货）。",
  "tw.customExtensionGallery.loading": "正在加载扩展库...（读外挂库中）",
  "tw.customExtensionGallery.loaded": "找到 {count} 个扩展（有{count}个外挂）",
  "tw.customExtensionGallery.error": "加载扩展库失败：{message}（寄了）",
  "tw.customExtensionGallery.add": "添加到扩展库（加入外挂库）",
  "tw.customExtensionGallery.load": "载（加载）",
  "tw.customExtensionGallery.unsandboxed": "这个扩展库的扩展不套沙盒跑",
  "tw.customExtensionGallery.unsandboxedWarning": "不套沙盒加载扩展很危险，不懂就别开。官方扩展始终不套沙盒，不受此选项影响。",
  "tw.customExtensionGallery.name": "自定义扩展库（自装外挂库）",
  "tw.customExtensionGallery.description": "自 URL 加载自定义扩展库（读外挂库）。",
  "mw.debugger.stagePauseButton": "舞台暂停按钮（场上暂停）",
  "mw.debugger.stagePauseButtonHelp": "在舞台上显示暂停按钮（一键急停）。",
  "mw.debugger.stageStepButton": "舞台单步按钮（一步一步来）",
  "mw.debugger.stageStepButtonHelp": "在舞台上显示单步执行按钮（一步一个脚印）。",
  "mw.debugger.threadGlow": "线程高亮（发光线程）",
  "mw.debugger.threadGlowHelp": "高亮正在执行的线程。",
  "mw.debugger.logClearGreenflag": "绿旗时清日志",
  "mw.debugger.logClearGreenflagHelp": "点绿旗时自动清空调试日志（重新起航）。",
  "mw.debugger.logGreenflag": "记录绿旗事件（记发车）",
  "mw.debugger.logGreenflagHelp": "在调试日志里记录绿旗点击事件。",
  "mw.debugger.logCloneCreate": "记录克隆创建（记分身）",
  "mw.debugger.logCloneCreateHelp": "在调试日志里记录克隆体创建事件（分身术施法记录）。",
  "mw.debugger.logFailedCloneCreation": "记录克隆失败（记分身失败）",
  "mw.debugger.logFailedCloneCreationHelp": "在调试日志里记录克隆体创建失败事件（分身术失败现场）。",
  "mw.debugger.logBroadcasts": "记录广播（记喊话）",
  "mw.debugger.logBroadcastsHelp": "在调试日志里记录广播消息（大喇叭喊话记录）。",
  "mw.debugger.fancyGraphs": "高级图表（花哨图表）",
  "mw.debugger.fancyGraphsHelp": "用高级图表显示性能数据（花里胡哨图表）。",
  "mw.projectMeta.contentLabel": "项目详情（作品档案）",
  "mw.projectMeta.sectionsAriaLabel": "项目详情分区（档案分区）",
  "mw.projectMeta.refreshing": "刷新中…（重刷中）",
  "mw.projectMeta.projectOverview": "项目概览（作品总览）",
  "mw.projectMeta.titleLabel": "标题（题目）",
  "mw.projectMeta.author": "作者（大佬）",
  "mw.projectMeta.created": "创建时间（出生日期）",
  "mw.projectMeta.lastEdited": "最后编辑（最后改动）",
  "mw.projectMeta.format": "格式（马甲）",
  "mw.projectMeta.untitled": "未命名（没起名）",
  "mw.projectMeta.saveToAddAuthor": "保存此项目以将 @{roturUsername} 添加为作者（署个名）。",
  "mw.projectMeta.signInToAddAuthor": "登录 Bilup Accounts（上号）并保存此项目以添加作者身份（留名）。",
  "mw.projectMeta.authorId": "作者 ID（大佬ID）",
  "mw.projectMeta.platform": "平台（阵营）",
  "mw.projectMeta.version": "版（版本）",
  "mw.projectMeta.vm": "VM（虚拟机）",
  "mw.projectMeta.userAgent": "用户代理（身份标识）",
  "mw.projectMeta.groupProject": "项目（作品）",
  "mw.projectMeta.groupAnalysis": "分析（解剖）",
  "mw.projectMeta.storageDescription": "当前大小、服务器用量和上传限制（体检报告）。",
  "mw.projectMeta.vmSizeNote": "编辑器里的大小直接来自 VM。最终压缩大小在上传时量（以实际为准）。",
  "mw.projectMeta.bilupLimits": "Bilup 上限：20 MB 压缩数据、1 GB 解压数据、50 MB 素材，单个素材最大 10 MB。（别塞太满）",
  "mw.projectMeta.sprites": "角（角色）",
  "mw.projectMeta.costumes": "形（造型）",
  "mw.projectMeta.sounds": "声（声音）",
  "mw.projectMeta.blocks": "积木（砖头）",
  "mw.projectMeta.extensions": "扩展（外挂）",
  "mw.projectMeta.none": "无（没）",
  "mw.projectMeta.projectData": "项目数据（作品数据）",
  "mw.projectMeta.assets": "素材（资源）",
  "mw.projectMeta.customAssets": "自定义素材（DIY资源）",
  "mw.projectMeta.fonts": "字体（字库）",
  "mw.projectMeta.uploadLimits": "上传限制（容量上限）",
  "mw.projectMeta.compressedProjectData": "服务器上的压缩项目数据（云上压缩包）",
  "mw.projectMeta.exactSizeFromUpload": "上次上传的确切大小（上传时的大小）",
  "mw.projectMeta.assetsInEditor": "编辑器里的素材",
  "mw.projectMeta.assetsEditorNote": "形、声、字体和自定义素材（素材列表）",
  "mw.projectMeta.largestSingleAsset": "最大的单个素材（最胖的）",
  "mw.projectMeta.expandedProjectData": "服务器上的解压项目数据（云上解压包）",
  "mw.projectMeta.variableDataInEditor": "编辑器里的变量和列表数据",
  "mw.projectMeta.fastEstimateFromVM": "来自 VM 的快速下限估算（机器估的）",
  "mw.projectMeta.breakdownDescription": "来自 VM 中实时素材、变量和列表的快速估算（大概数）。",
  "mw.projectMeta.largestParts": "最大的部分（最占地方的）",
  "mw.projectMeta.notRecorded": "没记录",
  "mw.projectMeta.loading": "载中…（读取中）",
  "mw.projectMeta.notUploaded": "未上传（没传）",
  "mw.projectMeta.editorEstimate": "编辑器估算（大概数）",
  "mw.projectMeta.storedOnBilup": "存在 Bilup",
  "mw.projectMeta.serverUsage": "服务器用量（云占用）",
  "mw.projectMeta.totalStored": "总存储（总占用）",
  "mw.projectMeta.maxSizeExceeded": "项目超存储上限了",
  "mw.projectMeta.largeSizeWarning": "项目有点大",
  "mw.projectMeta.sizeOK": "在存储限制内（稳）",
  "mw.devtools.profiler.title": "性能剖析（性能解剖）",
  "mw.devtools.profiler.start": "始（开始）",
  "mw.devtools.profiler.stop": "止（停止）",
  "mw.devtools.profiler.clear": "清除（清空）",
  "mw.devtools.profiler.empty": "点“始”在项目运行时记录每一帧的耗时（查帧率元凶）。",
  "mw.devtools.profiler.opcode": "积木（砖头）",
  "mw.devtools.profiler.count": "次数（几次）",
  "mw.devtools.profiler.total": "总耗时（总时间）",
  "mw.devtools.profiler.average": "平均（均值）",
  "mw.devtools.budget.title": "性能预算告警（性能超支预警）",
  "mw.devtools.budget.fps": "帧率（fps）",
  "mw.devtools.budget.memory": "内存占用（吃内存）",
  "mw.devtools.budget.thresholdFps": "帧率告警阈值（帧率红线）",
  "mw.devtools.budget.thresholdMemory": "内存告警阈值 (MB)（内存红线）",
  "mw.devtools.budget.ok": "在预算范围内（健康）",
  "mw.devtools.budget.over": "超出预算！（爆了）",
  "mw.devtools.budget.start": "始（开始）",
  "mw.devtools.budget.stop": "止（停止）",
  "mw.devtools.outline.title": "项目大纲（作品目录）",
  "mw.devtools.outline.sprites": "角（角色）",
  "mw.devtools.outline.stage": "舞台（场子）",
  "mw.devtools.outline.costumes": "形（造型）",
  "mw.devtools.outline.sounds": "声（声音）",
  "mw.devtools.outline.broadcasts": "广播消息（喊话记录）",
  "mw.devtools.outline.scripts": "顶层脚本（顶层代码）",
  "mw.devtools.outline.empty": "还没加载项目（空空如也）。",
  "mw.devtools.tracer.title": "事件追踪（事件监控）",
  "mw.devtools.tracer.start": "始（开始）",
  "mw.devtools.tracer.stop": "止（停止）",
  "mw.devtools.tracer.clear": "清除（清空）",
  "mw.devtools.tracer.empty": "点“始”以记录虚拟机事件（监视器启动）。",
  "rotur.bilupAccounts.name": "Bilup 账户（账号）",
  "rotur.bilupAccounts.description": "登录 Bilup（上号）并访问你的账户、权限和社交功能（混圈子）。",
  "rotur.bilupAccounts.docs": "Bilup 账户扩展文档（说明书）",
  "rotur.bilupAccounts.credits": "由 Bilup 团队提供（官方出品）",
  "rotur.bilupAccounts.bilupLogin.text": "登录 Bilup（上号）",
  "rotur.bilupAccounts.bilupLogin.tooltip": "打开 Bilup 账户登录窗口",
  "rotur.bilupAccounts.isLoggedIn.text": "已经登录了？",
};
