// geng 梗体中文翻译（由 generated-translations.json 恢复生成）
module.exports = {
  "mw.panel.console": "控制台（日志）",
  "mw.panel.buttonTitle": "作品问题与运行控制台（排雷区）",
  "mw.panel.buttonProblemsCount": "发现 {count} 个问题（有雷）",
  "mw.panel.buttonProblemsNone": "未发现问题（稳）",
  "mw.panel.clearConsole": "清空控制台（擦黑板）",
  "mw.panel.closePanel": "关闭面板（收起）",
  "mw.panel.noProblems": "未检测到问题（干净）",
  "mw.panel.consoleEmpty": "控制台为空（没日志）",
  "mw.panel.unknownTarget": "未知角色（无名氏）",
  "mw.panel.say": "{target} 说（吐槽）：{text}",
  "mw.panel.think": "{target} 心想：{text}",
  "mw.panel.question": "提问（发问）：{question}",
  "mw.panel.answer": "回答（回应）：{answer}",
  "mw.panel.runStart": "▶ 运行开始（点绿旗了）",
  "mw.panel.runStop": "■ 运行停止（急刹车）",
  "mw.panel.broadcast": "广播：{message}（喊话）",
  "mw.panel.compileError": "{target} · 编译错误（编译翻车）",
  "mw.panel.runtimeError": "{target} · 运行时错误（运行翻车）",
  "mw.panel.jumpToBlock": "点一下跳转到对应位置",
  "mw.panel.severity.error": "错（error）",
  "mw.panel.severity.warning": "警（warning）",
  "mw.panel.severity.info": "信（info）",
  "mw.panel.inspector.scriptNeverRuns": "脚本永远不会运行：缺帽子积木（没开头）",
  "mw.panel.inspector.listUnused": "列表「{name}」没用过（吃灰）",
  "mw.panel.inspector.variableUnused": "变量「{name}」没用过（吃灰）",
  "mw.panel.inspector.foreverNoWait": "无限循环里没有等待积木，可能卡死（死循环警告）",
  "mw.panel.inspector.cloudDuplicate": "云变量「{name}」重复定义了",
  "mw.panel.inspector.broadcastNoReceiver": "广播「{msg}」发出去了，但没人接收（对空气喊话）",
  "mw.panel.inspector.broadcastNeverSent": "广播「{msg}」有人接收，但从未发出过",
  "mw.panel.inspector.undefinedProcedure": "调用了没定义的自制积木：{proccode}",
  "mw.panel.inspector.unusedProcedure": "自制积木「{proccode}」从没被调用（吃灰）",
  "mw.panel.inspector.stageSource": "舞台（场子）",
  "mw.panel.inspector.spriteSource": "角色（崽崽）",
  "tw.packager.title": "打包器（一键封装）",
  "gui.menuBar.tools": "工具（工具箱）",
  "UNSUPPORT_TW_1": "以下积木不支持 TurboWarp（没兼容）",
  "UNSUPPORT_TW_2": "我们强烈建议别用它们（别作死）",
  "UNSUPPORT_TW_3": "它们只是为了和 MistWarp / Bilup 兼容",
  "gui.opcodeLabels.costumes": "造型（换装）",
  "gui.opcodeLabels.online": "在线？（上线没）",
  "CONTROL_SWITCH": "于 %1（切）",
  "CONTROL_CASE": "情况 %1（case）",
  "CONTROL_CASE_FALLTHROUGH": "情况 %1（case穿透）",
  "CONTROL_DEFAULT": "默认（否则）",
  "CONTROL_BREAK": "终止（跳出）",
  "CONTROL_CONTINUE": "继续（跳过）",
  "MOTION_POINTTOWARDS_XY": "面向 x: %1 y: %2（朝向）",
  "MOTION_POINTTOWARDS_XYFROM": "面向 x: %1 y: %2（自 x: %3 y: %4）",
  "LOOKS_COSTUMES": "造型（换装）",
  "OPERATORS_PI": "π（派）",
  "OPERATORS_NEWLINE": "换行（回车）",
  "shortcut-manager.title": "键盘快捷键（键盘大法）",
  "shortcut-manager.search": "搜快捷键...",
  "shortcut-manager.noResults": "没找到快捷键",
  "shortcut-manager.categories": "分类（分组）",
  "shortcut-manager.allShortcuts": "所有快捷键（全家桶）",
  "tw.menuBar.keyboardShortcuts": "键盘快捷键（键盘大法）",
  "tw.menuBar.superRefactor": "超级重构（一键换血）",
  "tw.menuBar.variableManager": "变量管理器（盒子管家）",
  "tw.menuBar.debugger": "调试器（抓虫神器）",
  "tw.menuBar.customGallery": "自定义扩展库（自装外挂库）",
  "tw.menuBar.assets": "素材库（资源仓库）",
  "tw.menuBar.projectMetadata": "项目信息（档案）",
  "tw.menuBar.help": "帮助（求救）",
  "tw.menuBar.showTutorial": "显示教程（新手村）",
  "onboarding.windowTitle": "RemixWarp 新手教程",
  "onboarding.step1.title": "欢迎来到 RemixWarp！（欢迎入坑）",
  "onboarding.step1.content": "跟这个简短导览走，看看让 RemixWarp 与众不同的狠活。",
  "onboarding.step2.title": "找啥都行",
  "onboarding.step2.content": "用搜索栏快速找积木、变量、广播和角色代码里的文字。",
  "onboarding.step3.title": "窗口管理器（多开王）",
  "onboarding.step3.content": "RemixWarp 的窗口管理器让你多任务拉满。窗口随便拖、随便调大小，需要时还能置顶。",
  "onboarding.step4.title": "调整面板大小（拉尺寸）",
  "onboarding.step4.content": "拖动调整手柄改工作区大小。舞台、背包和积木区都能按需定制。",
  "onboarding.step5.title": "个性化你的体验",
  "onboarding.step5.content": "在设置里挑好康的主题、主题色、壁纸和自定义字体，让 RemixWarp 变成你的形状。",
  "onboarding.step6.title": "一切就绪！（开冲！）",
  "onboarding.step6.content": "以后随时能从编辑菜单进这个教程。现在快去创造神作吧！",
  "onboarding.step7.title": "AI 助手",
  "onboarding.step7.content": "RemixWarp 内置强力 AI 工具，让你编程更快更聪明。用 AI Chat 求编程帮助，或用 AI Agent 跑自动化任务。",
  "onboarding.step8.title": "兼容性转换（格式搬家）",
  "onboarding.step8.content": "把项目转成其他基于 Scratch 的编辑器兼容格式。存为 Scratch、Turbowarp、02Engine、AstraEditor、Bilup 或 Gandi 格式都行。",
  "gui.menuBar.compatibility": "兼容性转换（格式搬家）",
  "gui.menuBar.compatibility.saveTo": "保存到（存成）",
  "gui.menuBar.compatibility.scratch": "Scratch",
  "gui.menuBar.compatibility.turbowarp": "Turbowarp",
  "gui.menuBar.compatibility.o2engine": "02Engine",
  "gui.menuBar.compatibility.astraeditor": "AstraEditor",
  "gui.menuBar.compatibility.Bilup": "Bilup",
  "onboarding.next": "下一步（走）",
  "onboarding.startCreating": "开始创作（冲！）",
  "onboarding.skipTutorial": "跳过教程（溜了）",
  "onboarding.replayTutorial": "重播教程（再看一遍）",
  "tw.addons.title": "插件（外挂）",
  "shortcut.category.file": "文件（档）",
  "shortcut.category.edit": "编辑（改）",
  "shortcut.category.view": "视图（看）",
  "shortcut.category.projectControls": "项目控制（开车）",
  "shortcut.category.editorNavigation": "编辑器导航（到处逛）",
  "shortcut.category.libraryAccess": "素材库访问（开库房）",
  "shortcut.category.spriteManagement": "角色管理（管崽崽）",
  "shortcut.category.windowManagement": "窗口管理（窗户）",
  "shortcut.category.superRefactor": "超级重构（大改造）",
  "shortcut.save": "保存（存档）",
  "shortcut.saveAsCopy": "另存为副本（存个备份）",
  "shortcut.loadFromComputer": "从电脑加载（导入）",
  "shortcut.packageProject": "打包项目（封装）",
  "shortcut.restorePoints": "还原点（读档）",
  "shortcut.settings": "设置（调）",
  "blockly.opcode.sound_seteffectto": "设置音效为（调音效）",
  "blockly.opcode.control_if_else": "如果…那么…否则",
  "blockly.opcode.control_wait_until": "等待直到（等到何时）",
  "blockly.opcode.control_repeat_until": "重复直到（循环到）",
  "blockly.opcode.control_for_each": "对每个执行（遍历）",
  "blockly.opcode.control_create_clone_of": "克隆…（分身术）",
  "blockly.opcode.control_delete_this_clone": "删除此克隆体（分身消消乐）",
  "blockly.opcode.operator_add": "加（+）",
  "blockly.opcode.operator_subtract": "减（-）",
  "blockly.opcode.operator_multiply": "乘（×）",
  "blockly.opcode.operator_divide": "除（÷）",
  "blockly.opcode.operator_random": "随机数（摇骰子）",
  "blockly.opcode.operator_gt": "大于（>）",
  "blockly.opcode.operator_lt": "小于（<）",
  "blockly.opcode.operator_equals": "等于（=）",
  "blockly.opcode.operator_and": "与（且）",
  "blockly.opcode.operator_or": "或（或者）",
  "blockly.opcode.operator_not": "不（非）",
  "blockly.opcode.operator_join": "连接（拼串）",
  "blockly.opcode.operator_letter_of": "…的第…个字符（第几个字）",
  "blockly.opcode.operator_length": "…的长度（几个字）",
  "blockly.opcode.operator_contains": "包含（含不含）",
  "blockly.opcode.operator_round": "四舍五入（取整）",
  "blockly.opcode.operator_mod": "除以…的余数（取余）",
  "blockly.opcode.argument_reporter_string_number": "文本或数字（字或数）",
  "blockly.opcode.argument_reporter_boolean": "布尔值（真假）",
  "shortcut.fullScreen": "切换全屏（放大招）",
  "shortcut.blocksTab": "积木选项卡（积木页）",
  "shortcut.costumesTab": "造型选项卡（换装页）",
  "shortcut.soundsTab": "声音选项卡（声音页）",
  "shortcut.greenFlag": "开始项目（发车）",
  "shortcut.stopAll": "停止所有（急刹车）",
  "shortcut.spriteLibrary": "打开角色库（崽崽库）",
  "shortcut.costumeLibrary": "打开造型库（换装库）",
  "shortcut.soundLibrary": "打开声音库（音效库）",
  "shortcut.extensionLibrary": "打开扩展库（外挂库）",
  "shortcut.extensionManager": "扩展管理器（外挂管家）",
  "shortcut.duplicateSprite": "复制角色（复制崽崽）",
  "shortcut.toggleBackpack": "切换背包（开书包）",
  "shortcut.deleteSprite": "删除角色（扔崽崽）",
  "shortcut.stageFullScreen": "切换舞台全屏（全屏化）",
  "shortcut.undo": "撤销（悔棋）",
  "shortcut.redo": "重做（再来）",
  "shortcut.copy": "复制（抄）",
  "shortcut.paste": "粘贴（贴）",
  "shortcut.cut": "剪切（剪）",
  "shortcut.aiChat": "打开 AI 聊天",
};
