// geng 梗体中文翻译（由 generated-translations.json 恢复生成）
module.exports = {
  "tw.gui.crashMessage.description": "抱歉，页面崩了。刷新一下再战（重启大法好）。",
  "tw.gui.defaultProjectTitle": "未命名の大作",
  "tw.guiDefaultTitle": "重构自由度（默认标题）",
  "tw.home.credit": "备注与鸣谢（幕后花絮）",
  "tw.home.description": "{APP_NAME} 能把作品编译成JavaScript，跑起来快到飞起。在上面输入Scratch官网的作品ID或链接就能开玩（打开新世界）。",
  "tw.home.instructions": "操作说明（使用指南）",
  "tw.input.tooltip": "把Scratch作品链接粘这儿！（粘贴即玩）",
  "tw.interpolationEnabled": "补帧（丝滑小连招）",
  "tw.invalidParameters.clones": "「clone」URL参数不合法（参数错了）",
  "tw.invalidParameters.fps": "「fps」URL参数不合法（帧率参数寄了）",
  "tw.invalidProject.error": "加载作品失败：",
  "tw.invalidProject.options": "可以从自动创建的还原点或别的备份里找回老版本（考古现场）。",
  "tw.invalidProject.reportIt": "上报（举报）",
  "tw.invalidProject.restorePoints": "看还原点（读档）",
  "tw.invalidProject.crossSync": "跨站同步（数据搬家）",
  "tw.invalidProject.title": "出大问题了（错误）",
  "tw.invalidProject.validationError": "这个错误一般意味着作品的一小块坏了，但别的地方还好好的。很好修，赶紧{reportIt}（小伤，能救）。",
  "tw.lightMode": "切到暗色主题（关灯了）",
  "tw.loadExtension.embedded": "这作品想用这段代码加载自定义外挂：",
  "tw.loadExtension.sandboxed": "就算在沙盒里跑，它还是能拿到IP地址、大概位置这些设备信息。用之前先确认你信得过这作者。",
  "tw.loadExtension.unsandboxed": "跑在沙盒外（裸奔）",
  "tw.loadExtension.unsandboxedWarning": "不套沙盒的外挂可能让作品报错、删你设置、偷你密码，或者整出别的幺蛾子。{APP_NAME} 开发者概不负责，风险自担。",
  "tw.loadExtension.url": "这作品想通过这个URL加载自定义外挂：",
  "mw.loadExtension.patching": "这作品里有JavaScript补丁积木（魔法积木）。",
  "mw.loadExtension.patchingWarning": "JavaScript补丁在 RemixWarp 里权限拉满。它可能偷你登录会话、接管你账号、改你项目和设置，或者跑恶意代码。只有信得过作者才继续（真·危险品）。",
  "mw.loadExtension.jsExecution": "这作品通过 {name} 扩展跑JavaScript。",
  "mw.loadExtension.jsExecutionWarning": "它在 RemixWarp 里权限拉满。可能偷你登录会话、接管你账号、改项目和设置，或者跑恶意代码。只有信得过作者才继续（能偷家の东西）。",
  "tw.loader.downloadingAssets": "搬素材中……（第 {complete} / {total} 个）",
  "tw.loader.loadingAssets": "读素材中……（第{complete}/{total}个）",
  "tw.loader.projectData": "加载作品中……（读盘中）",
  "tw.lockdownMode": "在苹果设备上，你得先关掉{lockdownMode}",
  "tw.lockdownMode2": "锁定模式（防误触）",
  "tw.menuBar.60off": "关掉 60 帧模式（帧率倒退）",
  "tw.menuBar.60on": "开启 60 帧模式（满血起飞）",
  "tw.menuBar.accent": "主题色（换色）",
  "tw.menuBar.addons": "外挂（插件）",
  "tw.menuBar.advanced": "进阶",
  "tw.menuBar.blockColors": "砖头颜色",
  "tw.menuBar.changeUsername": "改用户名",
  "tw.menuBar.cloudOff": "关云变量",
  "tw.menuBar.cloudOn": "开云变量",
  "tw.menuBar.cloudUnavailable": "云变量不可用（云挂了）",
  "tw.menuBar.cloudUnavailableAlert": "云变量用不了，八成是你开着编辑器。",
  "tw.menuBar.compileError": "{sprite}：{error}（编译翻车）",
  "tw.menuBar.desktopSettings": "桌面设置（电脑管家）",
  "tw.menuBar.moreSettings": "进阶设置（隐藏玩法）",
  "tw.menuBar.newFramerate": "帧率（fps）：",
  "tw.menuBar.newWindow": "新窗口（再来一扇）",
  "tw.menuBar.package": "打包作品（装盒发货）",
  "tw.menuBar.reportError1": "有些脚本编译时翻车了。",
  "tw.menuBar.reportError2": "这是bug，赶紧去报给开发团队。",
  "tw.menuBar.restorePoints": "还原点（读档）",
  "tw.menuBar.saveAs": "另存为 {file}（换个马甲）",
  "tw.menuBar.seeInside": "看源码（转到源代码）",
  "tw.menuBar.createRestorePoint": "创建还原点（存个档）",
  "tw.menuBar.runtime": "运行时（跑起来）",
  "tw.menuBar.extensions.addImport": "添加扩展（加外挂）",
  "tw.menuBar.extensions.manage": "扩展管理（管外挂）",
  "gui.extensionLibrary.chooseAnExtension": "选一个扩展",
  "gui.extensionLibrary.allTag": "全家桶（全部）",
  "gui.extensionLibrary.search": "搜扩展",
  "gui.extensionLibrary.added": "已入（已添加）",
  "gui.extensionLibrary.categories": "扩展（分类）",
  "gui.extensionLibrary.requires": "需要",
  "gui.extensionLibrary.collaboration": "合作（联机）",
  "tw.menuBar.customThemes": "自定义主题（DIY皮肤）",
  "tw.menuBar.theme": "主题（换皮肤）",
  "tw.menuBar.wallpaper": "壁纸（背景图）",
  "tw.menuBar.fonts": "字体（字库）",
  "tw.menuBar.menuBarAlign": "菜单栏对齐",
  "tw.menuBar.align.left": "靠左",
  "tw.menuBar.align.center": "居中",
  "tw.menuBar.align.right": "靠右",
  "tw.customThemes.create": "基于当前主题整个新的（复制皮肤）",
  "tw.customThemes.createGradient": "创建渐变主题（渐变色皮肤）",
  "tw.customThemes.import": "导入主题（导入皮肤）",
  "tw.customThemes.importPixel": "导入像素主题（像素皮肤）",
  "tw.customThemes.export": "导出全部主题（导出皮肤）",
  "tw.customThemes.empty": "没自定义主题（光秃秃）",
  "tw.wallpaper.noWallpaper": "无壁纸（光秃秃）",
  "tw.wallpaper.none": "无（没）",
  "tw.wallpaper.add": "添加（加一个）",
  "tw.wallpaper.opacity": "不透明度（透明度）：",
  "tw.wallpaper.darkness": "暗度（黑化程度）：",
  "tw.wallpaper.showGrid": "显示网格（打格子）",
  "tw.wallpaper.urlPlaceholder": "粘贴图片网址...（要图链接）",
  "tw.wallpaper.upload": "上传壁纸（换壁纸）",
  "tw.fonts.selectedFont": "已选字体（当前字）",
  "tw.fonts.default": "默认（出厂设置）",
  "tw.fonts.recentlyUsed": "最近用过",
  "tw.fonts.noRecent": "没有最近用过的字体",
  "tw.fonts.addFont": "添加字体（加字库）",
  "tw.mono": "单声道（一边响）",
  "tw.moreCloud": "云变量小课堂（了解更多）",
  "tw.notify.permission": "允许的话，浏览器可能会提醒你开通知，之后通知就自动放行了。",
  "tw.notify.title": "这作品想弹通知。",
  "tw.oldDownload": "保存到文件（下到电脑）",
  "tw.opcode.2000": "2000年至今的天数（千禧天数）",
  "tw.opcode.mousedown": "鼠标按下？",
  "tw.opcode.mousex": "鼠标的x坐标（指针横坐标）",
  "tw.opcode.mousey": "鼠标的y坐标（指针纵坐标）",
  "tw.openAdvanced": "打开进阶设置",
  "tw.openWindow.dangerous": "这网站没被 {APP_NAME} 开发者审核过，可能有危险或恶意代码（小心毒站）。",
  "tw.openWindow.title": "这作品想用这个URL打开新窗口或标签页：",
  "tw.paint.alpha": "不透明度（透明值）",
  "tw.paint.fonts.more": "添加更多字体……（字库加餐）",
  "tw.pen.stageSelected": "选的是舞台：只有有限的画笔积木能用（舞台上画笔受限）",
  "tw.privacy": "隐私政策（保密协议）",
  "tw.recordAudio.permission": "允许的话，浏览器可能会提醒你开麦克风，之后自动放行。",
  "tw.recordAudio.title": "这作品想用你的麦克风录音。可能包含转文字结果或原始音频，还可能分享给别人或服务器（小心被录音）。",
  "tw.recordVideo.permission": "允许的话，浏览器可能会提醒你开摄像头，之后自动放行。",
  "tw.recordVideo.title": "这作品想用你的摄像头录像。可能把图像分享给别人或服务器（小心被录像）。",
  "tw.redirect.dangerous": "这网站没被 {APP_NAME} 开发者审核过，可能有危险或恶意代码（慎点）。",
  "tw.redirect.title": "这作品想跳转到这个网址：",
  "tw.removedTrademarks": "某些含 Scratch 商标的物品就不列在这儿了。",
  "tw.restorePoints.1minute": "每分钟（60秒一次）",
  "tw.restorePoints.assets": "{n} 个素材（资源）",
  "tw.restorePoints.confirmDelete": "确定删掉「{projectTitle}」吗？删了就找不回来了（手滑警告）。",
  "tw.restorePoints.confirmDeleteAll": "确定删光所有还原点吗？没得后悔。",
  "tw.restorePoints.confirmLoad": "你还有没保存的更改。确定替换现有作品？",
  "tw.restorePoints.deleteAll": "全删了（删除全部）",
  "tw.restorePoints.description": "{APP_NAME} 会定时在电脑上存还原点，防止你忘存档。这是最后的救命稻草。电脑可能随时悄悄删掉这些还原点，别全指望它（自己存才稳）。",
  "tw.restorePoints.empty": "没找到还原点（没档可读）。",
  "tw.restorePoints.error": "读还原点出错：{error}",
  "tw.restorePoints.intervalOption": "{time}存一次档",
  "tw.restorePoints.loading": "加载中……（转圈圈）",
  "tw.restorePoints.minutes": "每 {n} 分钟（隔{n}分钟）",
  "tw.restorePoints.never": "永不（关掉）",
  "tw.restorePoints.off": "关掉还原点很危险（容易白干）。",
  "tw.restorePoints.size": "预计占空间：{size}",
  "tw.restorePoints.size2": "多个还原点共用的造型或声音只存一次（省空间）。",
  "tw.restorePoints.title": "还原点（存档）",
  "tw.restorePoints.localTab": "本地存档",
  "tw.restorePoints.cloudTab": "云端存档",
  "tw.restorePoints.cloudLoading": "加载中...",
  "tw.restorePoints.pushToCloud": "传上云端（上传存档）",
  "tw.restorePoints.pushingToCloud": "上传中...",
  "tw.restorePoints.cloudEmpty": "云端没找到存档。",
  "tw.restorePoints.cloudError": "云端存档加载失败：",
  "tw.restorePoints.versionFilter": "已过滤：版本 > {version}",
  "tw.alerts.cloudLinkCopied": "链接已复制到剪贴板（复制成功）",
  "tw.sample": "示例作品（样品）",
  "tw.saveAs": "另存为（存个副本）",
  "tw.saveTo": "保存到 {file}（存进）",
  "tw.scratchUnsafeCloud": "你要是建这个云变量，作品就会超过Scratch的 {number} 个变量上限，传到Scratch后有些云变量就废了（超限警告）。",
  "tw.securityManager.allow": "允许（放行）",
  "tw.securityManager.deny": "拒绝（不让）",
  "tw.securityManager.title": "扩展安全警告（外挂预警）",
  "tw.securityManager.trust": "允许的话，以后对同一站点的请求就自动放行了。",
  "tw.securityManager.why": "这会被用来下载图片或音频、做联机游戏、访问API，或者干坏事。会把你的IP、大概位置和其他数据分享给网站（会被开盒）。",
  "mw.securityManager.dontRun": "不跑（溜了溜了）",
  "mw.securityManager.ownerBypass": "全信了，跳过所有权限弹窗",
  "mw.securityManager.ownerBypassWarning": "要彻底信任这作品、跳过所有权限弹窗吗？只有你做的或你检查过的才继续。",
  "mw.securityManager.runFullAccess": "全裸权限跑（不套沙盒）",
  "mw.securityManager.runSandboxed": "沙盒里跑扩展",
  "tw.settingsModal.customStageSize": "自定义舞台大小（舞台尺寸）：",
};
