// geng 梗体中文翻译（由 generated-translations.json 恢复生成）
module.exports = {
  "rotur.bilupAccounts.isLoggedIn.tooltip": "若当前已登录 Bilup 账户（已上号）则为“真”",
  "rotur.bilupAccounts.username.text": "用户名（ID）",
  "rotur.bilupAccounts.username.tooltip": "当前登录的 Bilup 用户名（我的马甲）",
  "rotur.bilupAccounts.userId.text": "用户 ID（身份号）",
  "rotur.bilupAccounts.userId.tooltip": "当前登录的 Bilup 用户 ID（身份号）",
  "rotur.bilupAccounts.avatarUrl.text": "头像 URL（脸地址）",
  "rotur.bilupAccounts.avatarUrl.tooltip": "当前登录用户的头像链接（头像地址）",
  "rotur.bilupAccounts.isBilupPlus.text": "是 Bilup+ 会员？",
  "rotur.bilupAccounts.isBilupPlus.tooltip": "若用户拥有 Bilup+ 会员（尊贵VIP）则为“真”",
  "rotur.bilupAccounts.status.text": "在线状态（上没上线）",
  "rotur.bilupAccounts.status.tooltip": "获取当前用户的在线状态（查上线没）。",
  "rotur.bilupAccounts.statusSet.text": "设置在线状态为 %1（改状态）",
  "rotur.bilupAccounts.statusSet.tooltip": "设置当前用户的在线状态（改状态）。",
  "rotur.bilupAccounts.roles.text": "角色",
  "rotur.bilupAccounts.roles.tooltip": "获取当前用户在 Bilup 上的角色列表（身份标签）。",
  "rotur.bilupAccounts.permissions.text": "权限（钥匙）",
  "rotur.bilupAccounts.permissions.tooltip": "获取当前用户的权限列表（我有啥权限）。",
  "rotur.bilupAccounts.userLink.text": "用户主页链接（名片）",
  "rotur.bilupAccounts.userLink.tooltip": "当前登录用户的 Bilup 个人主页链接（名片）。",
  "rotur.bilupAccounts.notificationCount.text": "通知数量（小红点数量）",
  "rotur.bilupAccounts.notificationCount.tooltip": "获取当前用户的未读通知数量（小红点）。",
  "rotur.bilupAccounts.friendCount.text": "好友数量（基友数）",
  "rotur.bilupAccounts.friendCount.tooltip": "获取当前用户的好友数量（基友数）。",
  "rotur.bilupAccounts.incomingFriendRequests.text": "收到的好友请求（入的好友申请）",
  "rotur.bilupAccounts.incomingFriendRequests.tooltip": "获取发给当前用户的待处理好友请求列表。",
  "rotur.bilupAccounts.outgoingFriendRequests.text": "发出的好友请求（出的好友申请）",
  "rotur.bilupAccounts.outgoingFriendRequests.tooltip": "获取当前用户已发出的好友请求列表（发出去的好友申请）。",
  "rotur.bilupAccounts.friendList.text": "好友列表（基友名单）",
  "rotur.bilupAccounts.friendList.tooltip": "获取当前用户已加好友的用户名列表。",
  "rotur.bilupAccounts.addFriend.text": "加好友 %1",
  "rotur.bilupAccounts.addFriend.tooltip": "向指定用户发送好友请求（加好友）。",
  "rotur.bilupAccounts.removeFriend.text": "删好友 %1",
  "rotur.bilupAccounts.removeFriend.tooltip": "从好友列表里移除指定用户。",
  "rotur.bilupAccounts.acceptFriendRequest.text": "同意好友请求 %1",
  "rotur.bilupAccounts.acceptFriendRequest.tooltip": "接受来自指定用户的好友请求（同意加好友）。",
  "rotur.bilupAccounts.declineFriendRequest.text": "拒绝好友请求 %1（拒申请）",
  "rotur.bilupAccounts.declineFriendRequest.tooltip": "拒绝来自指定用户的好友请求（拒绝好友申请）。",
  "rotur.bilupAccounts.isFriend.text": "%1 是好友？",
  "rotur.bilupAccounts.isFriend.tooltip": "若指定用户是当前用户的好友（基友）则为“真”。",
  "rotur.bilupAccounts.isFollowing.text": "关注了 %1？",
  "rotur.bilupAccounts.isFollowing.tooltip": "若当前用户已关注指定用户（已点关注）则为“真”。",
  "rotur.bilupAccounts.follow.text": "关注 %1（点关注）",
  "rotur.bilupAccounts.follow.tooltip": "关注指定用户（点关注）。",
  "rotur.bilupAccounts.unfollow.text": "取关 %1",
  "rotur.bilupAccounts.unfollow.tooltip": "取消对指定用户的关注（取关）。",
  "rotur.bilupAccounts.followerCount.text": "粉丝数量（关注者数）",
  "rotur.bilupAccounts.followerCount.tooltip": "获取当前用户的粉丝数量（粉丝数）。",
  "rotur.bilupAccounts.followingCount.text": "关注数量（关注数）",
  "rotur.bilupAccounts.followingCount.tooltip": "获取当前用户已关注的人数（关注数）。",
  "rotur.bilupAccounts.profileUrl.text": "个人资料链接 %1（名片）",
  "rotur.bilupAccounts.profileUrl.tooltip": "获取指定用户的 Bilup 个人资料链接（名片）。",
  "rotur.bilupAccounts.featureEnabled.text": "%1 功能开了？",
  "rotur.bilupAccounts.featureEnabled.tooltip": "若指定功能对当前用户启用（开了没）则为“真”。",
  "rotur.bilupAccounts.getFeatureConfig.text": "获取功能配置 %1（读功能设置）",
  "rotur.bilupAccounts.getFeatureConfig.tooltip": "获取指定功能的配置数据（读配置）。",
  "rotur.bilupAccounts.fetchUsername.text": "获取用户名 %1（按ID查名）",
  "rotur.bilupAccounts.fetchUsername.tooltip": "通过用户 ID 获取用户名（查名字）。",
  "rotur.bilupAccounts.fetchUserId.text": "获取用户 ID %1（按名查ID）",
  "rotur.bilupAccounts.fetchUserId.tooltip": "通过用户名获取用户 ID（查身份号）。",
  "rotur.bilupAccounts.userExists.text": "用户 %1 存在？",
  "rotur.bilupAccounts.userExists.tooltip": "若指定用户名对应一个真实用户（真有这人）则为“真”。",
  "rotur.bilupAccounts.rawApi.text": "Bilup API 请求 %1 %2（裸调API）",
  "rotur.bilupAccounts.rawApi.tooltip": "向 Bilup API 发送任意请求（裸调接口）。需要权限（钥匙）。",
  "rotur.bilupAccounts.rawStorage.text": "Bilup 存储请求 %1 %2（裸调存储）",
  "rotur.bilupAccounts.rawStorage.tooltip": "向 Bilup 存储端点发送任意请求（裸调存储）。需要权限（钥匙）。",
  "rotur.bilupEconomy.name": "Bilup 经济（钱包）",
  "rotur.bilupEconomy.description": "获取积分、货币与交易信息（数钱快乐）。",
  "rotur.bilupEconomy.docs": "Bilup 经济扩展文档（钱包说明书）",
  "rotur.bilupEconomy.credits": "由 Bilup 团队提供（官方出品）",
  "rotur.bilupEconomy.balance.text": "余额 %1（钱包余额）",
  "rotur.bilupEconomy.balance.tooltip": "获取指定货币的余额（查余额）。",
  "rotur.bilupEconomy.currencyInfo.text": "货币信息 %1（钱的信息）",
  "rotur.bilupEconomy.currencyInfo.tooltip": "获取指定货币的详细信息（钱的信息）。",
  "rotur.bilupEconomy.transfer.text": "转账 %1 %2 给 %3（打钱）",
  "rotur.bilupEconomy.transfer.tooltip": "将指定数量的货币转账给指定用户（打钱）。",
  "rotur.bilupEconomy.transactionHistory.text": "交易记录（账本）",
  "rotur.bilupEconomy.transactionHistory.tooltip": "获取当前用户的交易历史（账本）。",
  "rotur.bilupEconomy.dailyStreak.text": "每日连签（连续签到）",
  "rotur.bilupEconomy.dailyStreak.tooltip": "获取当前用户的每日签到连击信息（连续签到）。",
  "rotur.bilupEconomy.claimDaily.text": "领每日奖励",
  "rotur.bilupEconomy.claimDaily.tooltip": "领取每日签到奖励（白嫖时刻）。",
  "rotur.bilupEconomy.shopItems.text": "商店物品（商店货）",
  "rotur.bilupEconomy.shopItems.tooltip": "获取 Bilup 商店物品列表（商店货架）。",
  "rotur.bilupEconomy.purchase.text": "购买 %1（剁手）",
  "rotur.bilupEconomy.purchase.tooltip": "购买指定商店物品（剁手）。",
  "rotur.bilupEconomy.ownedItems.text": "已拥有物品（仓库）",
  "rotur.bilupEconomy.ownedItems.tooltip": "获取当前用户已拥有的物品列表（仓库）。",
  "rotur.bilupKeys.name": "Bilup 密钥（钥匙）",
  "rotur.bilupKeys.description": "创建并管理 API 密钥（开锁钥匙）。",
  "rotur.bilupKeys.docs": "Bilup 密钥扩展文档（钥匙说明书）",
  "rotur.bilupKeys.credits": "由 Bilup 团队提供（官方出品）",
  "rotur.bilupKeys.list.text": "密钥列表（钥匙串）",
  "rotur.bilupKeys.list.tooltip": "获取当前用户的 API 密钥列表（钥匙串）。",
  "rotur.bilupKeys.create.text": "创建密钥 %1（配钥匙）",
  "rotur.bilupKeys.create.tooltip": "创建具有指定名称的新 API 密钥（配钥匙）。",
  "rotur.bilupKeys.revoke.text": "撤销密钥 %1（销钥匙）",
  "rotur.bilupKeys.revoke.tooltip": "撤销指定的 API 密钥（销钥匙）。",
  "rotur.bilupKeys.info.text": "密钥信息 %1（钥匙信息）",
  "rotur.bilupKeys.info.tooltip": "获取指定密钥的详细信息（钥匙信息）。",
  "rotur.bilupKeys.permissions.text": "密钥权限 %1（钥匙权限）",
  "rotur.bilupKeys.permissions.tooltip": "获取指定密钥的权限列表（钥匙权限）。",
  "rotur.bilupStatus.name": "Bilup 状态（在线状态）",
  "rotur.bilupStatus.description": "获取在线状态、活动与用户状态信息（谁在线一览）。",
  "rotur.bilupStatus.docs": "Bilup 状态扩展文档（在线状态说明书）",
  "rotur.bilupStatus.credits": "由 Bilup 团队提供（官方出品）",
  "rotur.bilupStatus.online.text": "%1 在线？",
  "rotur.bilupStatus.online.tooltip": "若指定用户当前在线（在线）则为“真”。",
  "rotur.bilupStatus.activity.text": "%1 的活动（在干嘛）",
  "rotur.bilupStatus.activity.tooltip": "获取指定用户的当前活动（在干嘛）。",
  "rotur.bilupStatus.customStatus.text": "%1 的自定义状态（个性签名）",
  "rotur.bilupStatus.customStatus.tooltip": "获取指定用户的自定义状态文本（个性签名）。",
  "rotur.bilupStatus.lastSeen.text": "%1 最后在线（何时下线）",
  "rotur.bilupStatus.lastSeen.tooltip": "获取指定用户最后一次在线的时间（何时下线）。",
  "rotur.bilupStatus.setCustomStatus.text": "设置自定义状态为 %1（改签名）",
  "rotur.bilupStatus.setCustomStatus.tooltip": "为当前用户设置自定义状态文本（改签名）。",
  "rotur.bilupStatus.clearCustomStatus.text": "清除自定义状态（删签名）",
  "rotur.bilupStatus.clearCustomStatus.tooltip": "清除当前用户的自定义状态（删签名）。",
  "rotur.bilupStatus.emote.text": "发送表情 %1（发颜文字）",
  "rotur.bilupStatus.emote.tooltip": "向当前用户的在线状态发送表情（发颜文字）。",
  "rotur.bilupSocial.name": "Bilup 社交（混圈子）",
  "rotur.bilupSocial.description": "发消息、关注用户并参与社区互动（吃瓜群众）。",
  "rotur.bilupSocial.docs": "Bilup 社交扩展文档（混圈子说明书）",
  "rotur.bilupSocial.credits": "由 Bilup 团队提供（官方出品）",
  "rotur.bilupSocial.sendMessage.text": "发消息 %1 给 %2",
  "rotur.bilupSocial.sendMessage.tooltip": "向指定用户发送一条消息（私聊）。",
  "rotur.bilupSocial.messageHistory.text": "消息记录（聊天记录）",
  "rotur.bilupSocial.messageHistory.tooltip": "获取与指定用户的消息历史（聊天记录）。",
  "rotur.bilupSocial.unreadCount.text": "未读消息数量（红点数）",
  "rotur.bilupSocial.unreadCount.tooltip": "获取当前用户的未读消息数量（红点恐惧）。",
  "rotur.bilupSocial.markRead.text": "标记消息已读 %1（已读标记）",
  "rotur.bilupSocial.markRead.tooltip": "标记与指定用户的消息为已读（已读不回）。",
  "rotur.bilupSocial.post.text": "发布动态 %1（发朋友圈）",
  "rotur.bilupSocial.post.tooltip": "发布一条社区动态（发朋友圈）。",
  "rotur.bilupSocial.feed.text": "动态流（朋友圈）",
  "rotur.bilupSocial.feed.tooltip": "获取当前用户的社区动态流（刷首页）。",
  "rotur.bilupSocial.likePost.text": "点赞动态 %1（一键三连）",
  "rotur.bilupSocial.likePost.tooltip": "点赞指定动态（一键三连）。",
  "rotur.bilupSocial.comment.text": "评论动态 %1：%2（评论区见）",
  "rotur.bilupSocial.comment.tooltip": "在指定动态下发表评论（前排吃瓜）。",
  "rotur.bilupSocial.joinGroup.text": "加入群组 %1（进群）",
  "rotur.bilupSocial.joinGroup.tooltip": "加入指定群组（进群）。",
  "rotur.bilupSocial.leaveGroup.text": "离开群组 %1（退群）",
  "rotur.bilupSocial.leaveGroup.tooltip": "离开指定群组（退群）。",
  "rotur.bilupSocial.groupList.text": "群组列表（群名单）",
  "rotur.bilupSocial.groupList.tooltip": "获取当前用户加入的群组列表（群名单）。",
  "rotur.bilupShop.name": "Bilup 商店（剁手店）",
  "rotur.bilupShop.description": "浏览商品、下单并管理你的订单（剁手专区）。",
  "rotur.bilupShop.docs": "Bilup 商店扩展文档（剁手店说明书）",
  "rotur.bilupShop.credits": "由 Bilup 团队提供（官方出品）",
  "rotur.bilupShop.products.text": "商品列表（货架）",
  "rotur.bilupShop.products.tooltip": "获取 Bilup 商店的商品列表（货架）。",
  "rotur.bilupShop.productInfo.text": "商品信息 %1（商品详情）",
  "rotur.bilupShop.productInfo.tooltip": "获取指定商品的详细信息（商品详情）。",
  "rotur.bilupShop.categories.text": "分类列表（分类）",
  "rotur.bilupShop.categories.tooltip": "获取商店分类列表（商品分类）。",
  "rotur.bilupShop.search.text": "搜索商品 %1（淘货）",
};
