// geng 梗体中文翻译（由 generated-translations.json 恢复生成）
module.exports = {
  "tw.extension.roturShop.description": "物品和装扮市场（剁手专区）。",
  "tw.extension.roturGroups.name": "Bilup Accounts 群组（拉帮结派）",
  "tw.extension.roturGroups.description": "社区、角色和群组经济（拉帮结派）。",
  "tw.extension.roturFiles.name": "Bilup Accounts 文件（网盘）",
  "tw.extension.roturFiles.description": "读取和管理你的 Bilup Accounts 文件存储（网盘）。",
  "tw.extension.patching.name": "Patching（打补丁）",
  "tw.extension.patching.description": "把 JavaScript 注入编译后的作品（魔法加成）。",
  "tw.extensionManager.loadedHeading": "已加载的扩展（已装外挂）",
  "tw.extensionManager.manyLoaded": "加载了 {count} 个扩展（外挂）",
  "tw.extensionManager.multipleExtensionsLoaded": "加载了 {count} 个扩展（外挂）",
  "tw.extensionManager.noBlocks": "没用积木（没砖头）",
  "tw.extensionManager.noneLoaded": "没加载扩展（空空）",
  "tw.extensionManager.noneLoadedDescription": "添加的扩展会显示在这里",
  "tw.extensionManager.oneExtensionLoaded": "加载了 1 个扩展（外挂）",
  "tw.extensionManager.oneLoaded": "加载了 1 个扩展（外挂）",
  "tw.extensionManager.refresh": "刷新（重刷）",
  "tw.extensionManager.summary": "{count} 个扩展 · {totalBlocks} 个积木（砖头）",
  "tw.extensionManager.title": "扩展管理器（外挂管家）",
  "tw.menuBar.resumeAutosave": "恢复自动保存（自动存档）",
  "tw.menuBar.pauseAutosave": "暂停自动保存（暂停存档）",
  "tw.customThemes.createDialog.name": "名称（名字）",
  "tw.customThemes.gradientDialog.name": "名称（名字）",
  "tw.customThemes.createDialog.description": "描述（选填）",
  "tw.customThemes.gradientCreator.preset": "预设（模板）",
  "tw.customThemes.gradientCreator.preview": "预览（瞅瞅）",
  "tw.customThemes.gradientCreator.colors": "颜色",
  "tw.customThemes.gradientCreator.removeColor": "移除（拿走）",
  "tw.customThemes.gradientCreator.addColor": "加颜色",
  "tw.customThemes.gradientCreator.direction": "方向",
  "tw.customThemes.gradientCreator.primaryColor": "主色调（主C色）",
  "tw.customThemes.createDialog.cancel": "算了（取消）",
  "tw.customThemes.createDialog.create": "创建（整一个）",
  "tw.customThemes.gradientEditor.title": "编辑渐变主题（调渐变皮肤）",
  "tw.customThemes.editorDialog.name": "名称（名字）",
  "tw.customThemes.gradientEditor.update": "更新（刷新）",
  "tw.customThemes.placeholder.gradientName": "我的渐变主题（渐变皮肤）",
  "tw.customThemes.placeholder.gradientDescription": "一个自定义渐变主题（渐变皮肤）",
  "tw.customThemes.placeholder.themeName": "我的自定义主题（DIY皮肤）",
  "tw.customThemes.placeholder.themeDescription": "基于当前设置的自定义主题（DIY皮肤）",
  "tw.customTheme.createWindowTitle": "创建自定义主题（DIY皮肤）",
  "tw.customTheme.createGradientWindowTitle": "创建渐变主题（渐变皮肤）",
  "tw.customThemes.gradientCreator.themeDetails": "主题详情（皮肤参数）",
  "tw.customThemes.gradientCreator.quickPresets": "快速预设（模板速取）",
  "tw.customThemes.gradientCreator.gradientEditor": "渐变编辑器（配色器）",
  "tw.customThemes.gradientCreator.copy": "复制（抄一份）",
  "tw.customThemes.gradientCreator.previewTheme": "预览主题（试试皮肤）",
  "tw.customThemes.gradientCreator.stopPreview": "停止预览（关预览）",
  "tw.customThemes.preset.sunset": "日落（夕阳红）",
  "tw.customThemes.preset.ocean": "海洋（深蓝）",
  "tw.customThemes.preset.forest": "森林（绿野）",
  "tw.customThemes.preset.purpleRain": "紫色雨（基佬紫雨）",
  "tw.customThemes.preset.fire": "火焰（燃起来）",
  "tw.customThemes.preset.aurora": "极光（北欧光）",
  "tw.customThemes.preset.space": "太空（星辰大海）",
  "tw.customThemes.preset.cherry": "樱桃（少女心）",
  "tw.customThemes.createPixel": "创建像素主题（像素皮肤）",
  "tw.customTheme.createPixelWindowTitle": "创建像素主题（像素皮肤）",
  "tw.customThemes.pixelCreator.themeDetails": "主题详情（皮肤参数）",
  "tw.customThemes.pixelDialog.name": "名称（名字）",
  "tw.customThemes.placeholder.pixelName": "我的像素主题（像素皮肤）",
  "tw.customThemes.placeholder.pixelDescription": "一个自定义像素艺术主题（像素风皮肤）",
  "tw.customThemes.pixelCreator.gridSettings": "网格设置（格子参数）",
  "tw.customThemes.pixelCreator.gridWidth": "宽度（横）",
  "tw.customThemes.pixelCreator.gridHeight": "高度（竖）",
  "tw.customThemes.pixelCreator.pixelSize": "像素大小（格子大小）",
  "tw.customThemes.pixelCreator.pixelEditor": "像素编辑器（涂格子）",
  "tw.customThemes.pixelCreator.currentColor": "当前颜色（现在这色）",
  "tw.customThemes.pixelCreator.clearCanvas": "清空画布（擦黑板）",
  "tw.customThemes.pixelCreator.backgroundColor": "背景颜色（画布填充）",
  "tw.customThemes.pixelCreator.nextBlock": "下一区块（下一个）",
  "tw.customThemes.pixelCreator.importImage": "导入图片（带图进来）",
  "tw.customThemes.pixelCreator.imagePreview": "图片预览（先看看）",
  "tw.customThemes.pixelCreator.insertColumn": "插入列（加一列）",
  "tw.customThemes.pixelCreator.apply": "应用（走起）",
  "tw.customThemes.pixelCreator.exportTheme": "导出主题（打包带走）",
  "tw.customThemes.pixelCreator.exportFormat": "选择导出格式（挑格式）",
  "tw.customThemes.pixelCreator.exportPNG": "PNG 图（图片格式）",
  "tw.customThemes.pixelCreator.exportPNGDescription": "像素感可能有点偏差",
  "tw.customThemes.pixelCreator.exportJSON": "JSON 文件（数据格式）",
  "tw.customThemes.pixelCreator.exportJSONDescription": "类似文本文件，无压缩算法（原始数据）",
  "tw.customThemes.pixelCreator.movePixelImage": "把像素化的图片移到：",
  "tw.customThemes.pixelCreator.left": "左边",
  "tw.customThemes.pixelCreator.center": "中间（正中）",
  "tw.customThemes.pixelCreator.right": "右边",
  "tw.customThemes.error.pixelThemeCreationFailed": "创建像素主题失败（寄了）：{errorMessage}",
  "tw.alertWindowTitle": "提示（弹窗）",
  "tw.customThemes.error.themeNameRequired": "主题名不能空着",
  "tw.customThemes.error.themeCreationFailed": "创建主题失败（寄了）：{errorMessage}",
  "tw.customThemes.error.gradientThemeCreationFailed": "创建渐变主题失败（寄了）：{errorMessage}",
  "tw.customThemes.error.gradientPresetNotFound": "没找到渐变预设",
  "tw.customThemes.error.gradientInfoLoadFailed": "无法加载此主题的渐变信息（读不到配色）",
  "tw.customThemes.error.gradientThemeLoadFailed": "加载渐变主题失败（寄了）：{errorMessage}",
  "tw.customThemes.error.noThemeSelectedForEditing": "没选要编辑的主题",
  "tw.customThemes.error.gradientThemeUpdateFailed": "更新渐变主题失败（寄了）：{errorMessage}",
  "tw.customThemes.confirmDeleteTheme": "确定删了主题「{themeName}」吗？",
  "tw.customThemes.error.themeExportFailed": "导出主题失败（寄了）：{errorMessage}",
  "tw.customThemes.import.error.themeAlreadyExists": "跳过：{skipped} 个主题（已有同款）",
  "tw.customThemes.import.error.themeImportFailed": "错误：{errorsCount}",
  "tw.customThemes.import.imageImported": "图「{fileName}」已导入为像素主题「{themeName}」",
  "tw.customThemes.error.imageImportFailed": "导入图片失败（寄了）：{errorMessage}",
  "tw.customThemes.import.success.importComplete": "导入完成！",
  "tw.customThemes.import.success.importedThemes": "导入了 {imported} 个主题",
  "tw.fonts.reset": "重置（复原）",
  "tw.fonts.googleFonts": "Google 字体（谷歌字库）",
  "tw.fonts.googleFontsSearch": "搜 Google 字体...",
  "mw.fonts.localFonts": "本地字体（本机字）",
  "mw.fonts.systemFontSearch": "输入字体名...",
  "mw.fonts.useLocalFont": "使用（走起）",
  "mw.fonts.windowTitle": "字体（字库）",
  "tw.customTheme.editGradientWindowTitle": "编辑渐变主题（改皮肤）",
  "tw.customTheme.title": "自定义主题（DIY皮肤）",
  "tw.customTheme.introduction": "你可以自定义界面的主题颜色。在下面输入喜欢的颜色，点「应用」来更新主题。",
  "tw.customTheme.maincolor": "主题色（主C色）",
  "tw.customTheme.maincolor.introduction": "选你喜欢的颜色，其他颜色自动填好",
  "tw.customTheme.apply": "应用（走起）",
  "tw.fonts.export": "导出（打包）",
  "tw.fonts.delete": "删除（扔了）",
  "tw.menuBar.autosaveSuccess": "项目自动保存成功！（自动存档OK）",
  "pm.paint.modeTools.merge": "合并（缝合）",
  "paint.modeTools.movementCenter": "移至中央（归位）",
  "paint.modeTools.brushSimplify": "平滑（丝滑）",
  "paint.modeTools.eraserSimplify": "平滑（丝滑）",
  "paint.modeTools.roundedCornerSize": "圆角大小（圆润程度）",
  "paint.modeTools.currentSideCount": "多边形边数（几条边）",
  "paint.modeTools.spikeRatio": "星形尖角比例（尖角程度）",
  "paint.modeTools.penSimplify": "平滑（丝滑）",
  "paint.modeTools.cut": "剪切（剪掉）",
  "pm.paint.modeTools.joinSpiked": "尖角（锐角）",
  "pm.paint.modeTools.joinRounded": "圆角（圆润）",
  "pm.paint.modeTools.joinBeveled": "斜角（切角）",
  "pm.paint.modeTools.endRounded": "圆角（圆头）",
  "pm.paint.modeTools.endSquared": "方角（平头）",
  "pm.paint.modeTools.subtract": "减去（挖掉）",
  "pm.paint.modeTools.mask": "遮罩（蒙版）",
  "pm.paint.modeTools.filter": "排除（滤掉）",
  "pm.paint.modeTools.leftAlign": "左对齐（靠左）",
  "pm.paint.modeTools.rightAlign": "右对齐（靠右）",
  "pm.paint.modeTools.centerAlign": "居中对齐（站中间）",
  "paint.paintEditor.more": "更多（还有）",
  "paint.triangleMode.triangle": "三角形（三角）",
  "paint.arrowMode.arrow": "箭头（箭头君）",
  "paint.shapeMode.shape": "形状（图形）",
  "paint.penMode.pen": "钢笔（笔）",
  "paint.modeTools.brushCircle": "圆形画笔（圆头笔）",
  "paint.modeTools.brushSquare": "方形画笔（方头笔）",
  "paint.modeTools.arrowTipResize": "按住 Alt + Shift 调整箭头大小（拉箭头）",
  "paint.sussyTool.category.shapes": "形状（图形）",
  "paint.sussyTool.category.symbols": "符号（记号）",
  "paint.sussyTool.category.objects": "物体（物件）",
  "paint.sussyTool.category.speech": "对话（气泡）",
  "paint.sussyTool.category.blocks": "方块（积木）",
  "paint.sussyTool.category.custom": "自定义（DIY）",
  "paint.sussyTool.shape.triangleRightAngle": "直角三角形（直角三角）",
  "paint.sussyTool.shape.chevronArrow": "V形箭头（V箭头）",
  "paint.sussyTool.shape.heart": "心形（爱心）",
  "paint.sussyTool.shape.smile": "笑脸（笑嘻嘻）",
};
