// geng 梗体中文翻译（由 generated-translations.json 恢复生成）
module.exports = {
  "shortcut.aiAgent": "打开 AI 助手",
  "shortcut.commandPalette": "命令面板（Ctrl+K）",
  "shortcut.problems": "开关问题面板（排雷区）",
  "shortcut.console": "开关控制台面板（日志区）",
  "shortcut-manager.recordingPrompt": "请同时按下键盘组合键来给 {name} 设快捷键",
  "shortcut-manager.recordingKeysPrompt": "已按下（当前按键）：{keys}",
  "shortcut-manager.recordingHint": "同时按住组合键（最多 5 个键），然后点保存。",
  "shortcut-manager.saveRecording": "保存（存）",
  "shortcut-manager.reRecord": "重新录制（重按）",
  "shortcut-manager.cancelRecording": "算了（取消）",
  "shortcut-manager.resetButton": "重置（复原）",
  "shortcut-manager.resetTitle": "重置键盘快捷键（恢复出厂）",
  "shortcut-manager.resetDesc": "选择要重置的范围：",
  "shortcut-manager.resetCurrent": "重置当前列表（{name}，恢复出厂）",
  "shortcut-manager.resetAll": "重置所有快捷键（恢复出厂）",
  "shortcut-manager.resetConfirmCancel": "算了（取消）",
  "shortcut-manager.categoryAll": "全部快捷键（全家桶）",
  "roadmap-modal.title": "编辑器硬核路线图（开发规划）",
  "roadmap-modal.subtitle": "MistWarp / RemixWarp 编辑器增强计划（画饼清单）",
  "roadmap-modal.direction": "方向",
  "roadmap-modal.status": "状态（进度）",
  "shortcut.closeWindow": "关闭窗口（关窗）",
  "shortcut.openCodeEditor": "打开代码编辑器（开码器）",
  "shortcut.openGitPanel": "打开 Git 面板",
  "shortcut.toggleExplorer": "开关资源管理器（切换工位）",
  "shortcut.toggleZenMode": "开关禅模式（隐身）",
  "tw.customThemes.createDialog.createButton": "创建（整一个）",
  "tw.tutorialModal.tutorial1.title": "RemixWarp 入门教程（新手村）",
  "tw.tutorialModal.tutorial1.description": "学习 RemixWarp 编辑器的基本操作",
  "gui.aiModal.chatTitle": "AI 聊天（跟AI唠嗑）",
  "gui.aiModal.agentTitle": "AI 助手（AI打工人）",
  "gui.aiModal.baiduTitle": "百度 AI（度娘）",
  "gui.stageHeader.stageSizeInitial": "恢复默认大小（回原样）",
  "tw.compatibilityModal.title": "兼容性转换（格式搬家）",
  "tw.compatibilityModal.selectEditor": "选择目标编辑器（挑目标）",
  "tw.compatibilityModal.issuesFound": "发现不兼容问题（有坑）",
  "tw.compatibilityModal.warnings": "警告（注意）",
  "tw.compatibilityModal.success": "转换成功！文件已下载。（成了）",
  "tw.compatibilityModal.cancel": "算了（取消）",
  "tw.compatibilityModal.converting": "转换中...（搬家进行时）",
  "tw.compatibilityModal.convertAndDownload": "转换并下载（搬家并拿走）",
  "tw.compatibilityModal.conversionText": "从 {source} 转成 {target}",
  "bl.warptheme.title": "WarpTheme 主题商店（主题商城）",
  "bl.warptheme.searchPlaceholder": "搜主题...",
  "bl.warptheme.newest": "最新（新货）",
  "bl.warptheme.likes": "最多喜欢（赞最多）",
  "bl.warptheme.name": "名称（名字）",
  "bl.warptheme.allPlatforms": "所有平台（全平台）",
  "bl.warptheme.RemixWarp": "RemixWarp",
  "bl.warptheme.allColors": "所有颜色（全色系）",
  "bl.warptheme.red": "红（中国红）",
  "bl.warptheme.orange": "橙（橘里橘气）",
  "bl.warptheme.yellow": "黄（阿黄）",
  "bl.warptheme.green": "绿（原谅色）",
  "bl.warptheme.blue": "蓝（yyds蓝）",
  "bl.warptheme.purple": "紫（基佬紫）",
  "bl.warptheme.createTheme": "创建主题（整皮肤）",
  "bl.warptheme.loading": "正在加载主题...（读皮肤中）",
  "bl.warptheme.error": "加载主题失败（寄了）",
  "bl.warptheme.likesCount": "{count} 个赞",
  "bl.warptheme.downloadsCount": "{count} 次下载",
  "bl.warptheme.applyTheme": "应用（穿上）",
  "bl.warptheme.downloadTheme": "下载主题（扒下来）",
  "bl.warptheme.openInWarpTheme": "在 WarpTheme 中打开（去看皮肤）",
  "tw.accent.greenv2": "绿 V2（绿2.0）",
  "tw.accent.darkgreen": "深绿（绿得发黑）",
  "tw.accent.light-blue": "浅蓝（天蓝）",
  "tw.accent.pinkv2": "粉红 V2（猛男粉）",
  "tw.accent.ce": "CE粉（电竞粉）",
  "tw.accent.miku": "Miku绿（葱葱绿）",
  "tw.accent.magenta": "洋红（品红）",
  "tw.accent.ty": "天依蓝（Vocaloid）",
  "tw.accent.oubi": "Oubi（欧比）",
  "tw.accent.omniblue": "OM蓝（一键变蓝）",
  "mw.accent.bi": "炫彩01（双色）",
  "mw.accent.pan": "炫彩02（三色）",
  "mw.accent.lesbian": "炫彩03（橘里橘气）",
  "mw.accent.nonbinary": "炫彩04（黄白紫黑）",
  "mw.accent.asexual": "炫彩05（灰白紫）",
  "mw.accent.vaporwave": "蒸汽波（复古赛博）",
  "mw.accent.matrix": "矩阵（黑客帝国）",
  "mw.accent.honey": "蜂蜜（甜到齁）",
  "tw.accent.custom": "自定义（自己调）",
  "tw.theme.gui.genesis light": "创世浅色（亮色皮肤）",
  "tw.theme.gui.modernwhite": "现代白（白色皮肤）",
  "tw.theme.gui.genesis dark": "创世深色（暗色皮肤）",
  "tw.theme.gui.deepdark": "深邃黑暗（黑到底）",
  "mw.menuBar.myStuff": "我的作品（我的存货）",
  "mw.menuBar.notifications": "通知（小红点）",
  "gui.menuBar.saveToBilup": "保存到 Bilup（云端存档）",
  "gui.menuBar.todo": "待办（备忘录）",
  "gui.menuBar.aiAgent": "AI 助手（AI打工人）",
  "tw.login.button": "登录（上号）",
  "mw.rotur.menuBar.login": "登录（上号）",
  "mw.rotur.accountMenu.profile": "个人资料（主页）",
  "mw.rotur.accountMenu.leaderboard": "排行榜（战力榜）",
  "mw.rotur.accountMenu.settings": "设置（调）",
  "mw.rotur.accountMenu.infoButton": "RemixWarp 说明（说明书）",
  "mw.rotur.accountMenu.switchAccount": "切换账号（换号）",
  "mw.rotur.accountMenu.signOut": "退出登录（下线）",
  "mw.roturLogin.contentLabel": "用 Bilup Accounts 登录（上号）",
  "mw.roturLogin.loggedInContentLabel": "Bilup 里的 Bilup Accounts",
  "mw.roturLogin.loggedInTitle": "Bilup 里的 Bilup Accounts",
  "mw.roturLogin.connectTitle": "把 RemixWarp 连上 Bilup Accounts",
  "mw.roturLogin.subtitle": "登录后能用在线状态、个人头像，还有主题和设置的云同步（云存档yyds）。",
  "mw.roturLogin.loggedInSubtitle": "你已以 {username} 身份登录。下面是你账号开了的功能。",
  "mw.roturLogin.unlockTitle": "你将解锁的功能",
  "mw.roturLogin.comingSoonTitle": "敬请期待（画饼区）",
  "mw.roturLogin.notNow": "先不登录（再逛逛）",
  "mw.roturLogin.continue": "用 Bilup Accounts 继续（继续上号）",
  "mw.roturLogin.busyContinue": "正在打开 Bilup Accounts...（开登录页中）",
  "mw.roturLogin.close": "阖（关掉）",
  "mw.roturLogin.sessionNotReady": "Bilup Accounts 会话还没就绪，稍后再试（别急）。",
  "mw.roturLogin.footnote": "于 accounts.bilup.org 安全登录。你的账号支持在线状态、云同步和 Bilup Git。",
  "mw.roturLogin.feature.editTitle": "秀出你在编辑啥",
  "mw.roturLogin.feature.editDesc": "在你的 Bilup Accounts 个人资料上分享 Bilup 活动（刷存在感）。",
  "mw.roturLogin.feature.cloudTitle": "云端主题与设置（云同步皮肤）",
  "mw.roturLogin.feature.cloudDesc": "登录后在不同设备间同步主题和设置（换设备不迷路）。",
  "mw.roturLogin.feature.gitTitle": "Git 窗口里的 Bilup Git",
  "mw.roturLogin.feature.gitDesc": "于 git.bilup.org 上建仓库、推项目、克隆别人的项目（仓库随便开）。",
  "mw.roturLogin.feature.friendsTitle": "好友与协作邀请（基友组队）",
  "mw.roturLogin.feature.friendsDesc": "看 Bilup 上的在线好友并邀请他们一起肝（组队开黑）。",
  "mw.share.saving": "保存中…（存档中）",
  "mw.share.thumbnailNotice": "没法附带缩略图，就这么光着发布吧。",
  "mw.share.couldNotSave": "保存失败（寄了）",
  "mw.share.couldNotAcceptAgreement": "协议都接受不了（离谱）。",
  "mw.share.remix": "改编（整活）",
  "mw.share.update": "更新（升级）",
  "mw.share.save": "存（存档）",
  "mw.share.checkStorage": "看项目存储（查仓库）",
  "mw.share.uploadAgreement": "上传协议（用户条款）v{version}",
  "mw.share.cancel": "废（算了）",
  "mw.share.accepting": "接受中…（正在勾同意）",
  "mw.share.acceptAgreement": "接受 v{version} 并{action}（勾了就开干）",
  "mw.share.savedAndShared": "你的项目已保存并已分享（已发布，开冲）。",
  "mw.share.savedPrivate": "你的项目已保存到 Bilup。它会保持私有，直到你从项目页面主动分享（没开公开没人看得到）。",
  "mw.share.close": "阖（关掉）",
  "mw.share.openProjectPage": "打开项目页面（看项目页）",
  "mw.share.updateDescription": "把此项目的当前版本上传到 Bilup。标题和缩略图保持不变，请去项目页面编辑。",
  "mw.share.title": "标题（题目）",
  "mw.share.untitled": "未命名（没起名）",
  "mw.share.thumbnail": "缩略图（小图）",
  "mw.share.thumbnailAlt": "项目缩略图（封面）",
  "mw.share.noPreview": "没预览（无图）",
  "mw.share.useCurrentCanvas": "用当前画布",
  "mw.share.uploadImage": "上传图片（传图）",
  "mw.share.windowTitleSave": "保存到 Bilup（云存档）",
  "mw.share.windowTitleRemix": "改编到 Bilup（魔改上传）",
  "mw.share.windowTitleUpdate": "更新 Bilup 项目（升级上传）",
  "mw.info.heading": "RemixWarp 说明（说明书）",
  "mw.info.warningText": "登录及其他附属功能均同步自 github.com/bilup。（来源官网）",
  "mw.info.sectionTitle": "说明（简介）",
  "mw.info.paragraph1": "登录以及其他附属功能均同步自 github.com/bilup，所有关于此功能及附属功能的 bug 请先在 https://com.bilup.org/editor 操作确认它真是 RemixWarp 独有 bug 再报（别拿别人的锅甩给我们）。",
  "mw.info.paragraph2": "所有关于本功能及附属功能的使用以及操作反馈，均为 github.com/bilup 源代码提供（除了本说明）所有让您进行包括但不限于信息收集 / 支付等一系列的操作，RemixWarp 均不会进行保存等行为（你充的钱全进了 Bilup 团队的口袋）。",
  "mw.info.usageSectionTitle": "用（使用说明）",
  "mw.info.usageParagraph1": "RemixWarp 用本功能或附属功能时可能和 Bilup 有点不一样（别慌）。",
};
