// geng 梗体中文翻译（由 generated-translations.json 恢复生成）
module.exports = {
  "mw.tree.explorer": "资源管理（赛博工位）",
  "mw.tree.title": "资源管理器（赛博工位）",
  "mw.tree.costumes": "换装",
  "mw.tree.sounds": "声音",
  "mw.tree.variables": "盒子（变量）",
  "mw.tree.lists": "小本本（列表）",
  "mw.tree.broadcasts": "大喇叭（广播）",
  "mw.tree.procedures": "自制砖头（我的积木）",
  "mw.tree.empty": "空空如也，没崽崽",
  "mw.panel.terminal": "终端（黑科技）",
  "gui.menuBar.02agent": "02Agent（AI打工仔）",
  "gui.alerts.twCustomBlockPercent": "自制积木里不让放百分号，别搞事",
  "gui.backpack.searchPlaceholder": "在小书包里搜点啥...",
  "gui.backpack.createFolder": "新建文件夹（新窝）",
  "gui.backpack.showWorkspace": "亮出工作区",
  "gui.backpack.hideWorkspace": "藏起工作区",
  "gui.backpack.allLabel": "全家桶（全部）",
  "gui.backpack.workspaceLabel": "工位（工作区）",
  "gui.backpack.folderLabel": "小抽屉（文件夹）",
  "gui.backpack.errorBackpack": "书包加载寄了，蚌埠住了",
  "gui.backpack.loadingBackpack": "书包加载ing……",
  "gui.backpack.emptyBackpack": "书包空空如也",
  "gui.backpack.more": "还有好货（更多）",
  "gui.collaboration.captchaTitle": "人机验证（你是真人还是AI？）",
  "gui.collaboration.captchaDescription": "先证明你没开挂，才能建房。",
  "gui.collaboration.captchaLabel": "交卷（答案）",
  "gui.collaboration.verifyCaptcha": "验货（验证）",
  "gui.collaboration.newCaptcha": "换一题（新挑战）",
  "gui.collaboration.cancelVerification": "不玩了（取消）",
  "tw.accent.blue": "蓝色（yyds蓝）",
  "tw.accent.purple": "紫色（基佬紫）",
  "tw.accent.rainbow": "彩虹色（花里胡哨）",
  "tw.accent.red": "红色（中国红）",
  "tw.accent.orange": "橙色（橘里橘气）",
  "tw.accent.yellow": "黄色（阿黄）",
  "tw.accent.green": "绿色（原谅色）",
  "tw.accent.trans": "流光（赛博朋克）",
  "tw.accent.gay": "欢愉（彩虹小马）",
  "tw.accent.rotur": "旋涌（爱的魔力转圈圈）",
  "tw.accent.pink": "粉红色（猛男粉）",
  "tw.accent.sunset": "日落（夕阳红）",
  "tw.accent.ocean": "海洋（深蓝诱惑）",
  "tw.accent.aurora": "极光（北欧风光）",
  "tw.accent.cosmic": "宇宙（星辰大海）",
  "tw.accent.fire": "火焰（燃起来了）",
  "tw.accent.nebula": "星云（璀璨星河）",
  "tw.accent.lavender": "薰衣草（普罗旺斯）",
  "tw.accent.mint": "薄荷（清凉一夏）",
  "tw.accent.cherry": "樱桃（少女心）",
  "tw.accent.sky": "天空（晴空万里）",
  "tw.accent.forest": "森林（绿野仙踪）",
  "tw.accent.coral": "珊瑚（海底两万里）",
  "tw.accent.eggplant-purple": "紫茄（茄子精）",
  "tw.accent.green-tea": "绿茶（bushi）",
  "tw.accent.pale-blue": "淡蓝跃迁（量子纠缠）",
  "tw.accent.02e": "02引擎（二次元启动）",
  "tw.accent.ae": "Astra编辑器（星尘の力）",
  "tw.alerts.creatingRestorePoint": "正在存档还原点……",
  "tw.alerts.lostPeripheralConnection": "和 {extensionName} 的连线啪叽断了",
  "tw.alerts.restorePointError": "存档失败，寄了",
  "tw.alerts.restorePointSuccess": "存档成功！去「文件」菜单里翻还原点",
  "tw.alerts.savedToDisk": "已保存到电脑，稳了",
  "tw.backpack.rename": "新名字：",
  "tw.blockColors.custom": "在插件设置里自己调（DIY走起）",
  "tw.blockColors.dark": "深色（夜猫子模式）",
  "tw.blockColors.highContrast": "高对比度（老花眼友好）",
  "tw.blockColors.three": "原汁原味（默认样式）",
  "tw.blocks.PROCEDURES_DOCS": "返回值咋用（干货教程）",
  "tw.blocks.PROCEDURES_RETURN": "返回值 {v}（吐出来）",
  "tw.blocks.PROCEDURES_TO_REPORTER": "改成返回值积木（转行报告员）",
  "tw.blocks.PROCEDURES_TO_STATEMENT": "改成命令积木（转行命令员）",
  "tw.blocks.addons": "外挂合集（插件）",
  "tw.blocks.buttonIsDown": "鼠标[MOUSE_BUTTON]键按着吗？",
  "tw.blocks.lastKeyPressed": "最后按的键（键来！）",
  "tw.blocks.mouseButton.middle": "(1) 中键（滚轮君）",
  "tw.blocks.mouseButton.primary": "(0) 左键（主C）",
  "tw.blocks.mouseButton.secondary": "(2) 右键（副C）",
  "tw.blocks.openDocs": "看文档（查攻略）",
  "tw.browserModal.desc": "浏览器太老就退退退！快去更新Chrome、火狐、Edge或Safari。",
  "tw.cantUseCloud": "你造的云变量，得传到支持云变量的网站，或者用 {packager} 这类工具打包才有用，不然纯白搭。",
  "tw.changeUsername.cannotChangeWhileRunning": "作品跑着呢，改不了名字，稍等。",
  "tw.clipboard.danger": "剪贴板里要是有密码之类的东西，这作品可能会把它分享给别人或服务器，危险操作慎点！",
  "tw.clipboard.permission": "有些浏览器不让读剪贴板。允许的话，以后读剪贴板就自动放行了。",
  "tw.clipboard.title": "这作品想看你的剪贴板（想偷看你复制了啥）。",
  "tw.cloudProvider": "云变量服务器是 {name} 提供的（背后的大佬）。",
  "tw.cloudServers": "挑个离你近的服务器：",
  "tw.code": "源代码（核心机密）",
  "tw.confirmIncompatibleExtension": "这个外挂和Scratch不兼容，用它做的作品传不上Scratch网站。确定要开吗？",
  "tw.createdBy": "作者（大佬）：",
  "tw.customCloudServer": "用自定义云变量服务器：{server}",
  "tw.customExtension.description": "从URL、文件或JavaScript源码加载自定义外挂（万物皆可加载）。",
  "tw.customExtension.name": "自定义外挂",
  "tw.customExtensionModal.file": "文件（本地货）",
  "tw.customExtensionModal.load": "加载（走你！）",
  "tw.customExtensionModal.promptFile": "选一个外挂的JavaScript文件（或拖进来）：",
  "tw.customExtensionModal.promptText": "粘贴外挂的JavaScript源码：",
  "tw.customExtensionModal.promptURL": "输入外挂的URL：",
  "tw.customExtensionModal.text": "文本（码农区）",
  "tw.customExtensionModal.title": "加载自定义外挂",
  "tw.customExtensionModal.trusted": "这外挂来自可信来源，所以放它出沙盒（大佬带飞）。",
  "tw.customExtensionModal.unsandboxed": "跑在沙盒外（裸奔模式）",
  "tw.customExtensionModal.unsandboxedWarning1": "不套沙盒跑外挂很危险，不知道自己在干啥就别开。",
  "tw.customExtensionModal.unsandboxedWarning2": "不套沙盒的外挂可能让作品报错、删你设置、偷你密码，或者整出别的幺蛾子。{APP_NAME} 开发者概不负责，后果自负。",
  "tw.customExtensionModal.untrusted": "为保安全，来路不明的外挂一律关小黑屋（沙盒里跑）。",
  "tw.extensionLoadChoice.title": "加载外挂",
  "tw.extensionLoadChoice.extensionName": "外挂：{name}",
  "tw.extensionLoadChoice.loadFromURL": "从URL加载（在线整活）",
  "tw.extensionLoadChoice.loadFromFile": "从本地文件加载（离线整活）",
  "tw.extensionLoadChoice.or": "或（二选一）",
  "tw.customReporters.description": "自制积木也能返回值（积木会说话了）",
  "tw.customReporters.name": "自定义返回值（自带返程票）",
  "tw.darkMode": "切到亮色主题（闪瞎眼警告）",
  "tw.desktopCloud": "在桌面版里，云变量只在这台电脑上的所有窗口间同步。想全球同步就把作品传到Scratch或用 {packager} 这类工具。",
  "tw.documentation": "文档（说明书）",
  "tw.embed.persistent": "允许的话，以后同一站点的嵌入内容就自动放行了。",
  "tw.embed.risks": "就算嵌入内容在沙盒里跑，它还是能拿到你的IP地址、大概位置这些设备信息（会被开盒）。",
  "tw.embed.title1": "这作品想在舞台上嵌HTML内容：",
  "tw.embed.title2": "这作品想在舞台上嵌在线内容：",
  "tw.extensionGallery.error": "加载扩展库翻车了。",
  "tw.extensionGallery.loading": "扩展库加载ing……",
  "tw.extensionGallery.more": "TurboWarp扩展库（更多外挂）",
  "tw.extensionGallery.name": "TurboWarp扩展库（外挂集市）",
  "tw.extension.faceSensing.name": "人脸侦测（AI认脸）",
  "tw.extension.faceSensing.description": "用摄像头侦测人脸（镜头怼脸）。",
  "tw.favorite": "收藏（码住）",
  "tw.featuredProjectsStudio": "去 Scratch 看工作室",
  "tw.feedback": "反馈与漏洞提交（有bug快说）",
  "tw.feedbackButton": "{APP_NAME} 反馈（有bug快说）",
  "tw.fetch.title": "这作品想连这个网站：",
  "tw.fileInput.none": "没选文件（空空如也）。",
  "tw.fileInput.selected": "选中（已挑）：{names}",
  "tw.fonts.add": "添加（走起）",
  "tw.fonts.custom.file": "从电脑挑个字体文件",
  "tw.fonts.custom.name": "给字体起个名：",
  "tw.fonts.custom1": "从文件添加字体（本地字库）",
  "tw.fonts.custom2": "通常Scratch里不认。支持的格式：{formats}",
  "tw.fonts.deleteConfirm": "确定删掉「{font}」吗？所有矢量造型里这个字体会换成备用字体（换个马甲）。",
  "tw.fonts.fallback": "字体加载失败或被删时，用这个备用字体：",
  "tw.fonts.list": "已装字体：",
  "tw.fonts.none": "还没加字体（字库空空）。",
  "tw.fonts.readError": "读字体文件失败：{error}",
  "tw.fonts.system": "系统字体（原生出品）",
  "tw.fonts.system.name": "输入电脑里的字体名。这字体别人不一定看得到（独享系列）。",
  "tw.fonts.system1": "添加系统字体（系统自带）",
  "tw.fonts.system2": "Scratch里可能能用，但别人能不能看到全看缘分。",
  "tw.fonts.title": "字体（字字珠玑）",
  "tw.footer.credits": "鸣谢（感谢名单）",
  "tw.footer.disclaimer": "{APP_NAME} 不是Scratch、Scratch团队或Scratch基金会的（纯路人）。",
  "tw.footer.documentation": "文档（攻略手册）",
  "tw.footer.donate": "捐赠（打钱）",
  "tw.footer.embed": "把作品嵌到网站上（搬到别人家）",
  "tw.footer.parameters": "网址参数（参数全家桶）",
  "tw.footer.scratchDisclaimer": "Scratch 是 Scratch 基金会的一个项目，在 {scratchDotOrg} 免费使用。",
  "tw.fps": "{framerate} 帧（丝滑流畅）",
  "tw.geolocate.permission": "允许的话，浏览器可能会弹窗问你要位置权限（暴露坐标）。",
  "tw.geolocate.title": "这作品想知道你的位置（想定位你）。",
};
