/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "日常一句",
  "description": "在编辑器状态栏显示每日一句/随机短语，并提供插件设置面板来调整切换间隔。",
  "credits": [
    {
      "name": "你",
      "url": ""
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [],
  "settings": [
    {
      "dynamic": true,
      "name": "启用 日常一句",
      "id": "enable_daily_quote",
      "type": "boolean",
      "default": true
    }
  ],
  "tags": [
    "ui",
    "daily",
    "quote"
  ],
  "enabledByDefault": true
};
export default manifest;
