/* generated by pull.js */
const manifest = {
    "editorOnly": true,
    "name": "舞台相机控制",
    "description": "为舞台添加相机控制功能，支持缩放、平移和全屏。在使用视频侦测或人脸检测扩展时特别有用。",
    "credits": [
        {
            "name": "笑小朗"
        }
    ],
    "userscripts": [
        {
            "url": "userscript.js",
            "matches": ["projects"]
        }
    ],
    "userstyles": [
        {
            "url": "style.css",
            "matches": ["projects"]
        }
    ],
    "settings": [
        {
            "name": "显示相机控制",
            "id": "showControls",
            "type": "boolean",
            "default": false
        },
        {
            "name": "不使用时自动隐藏",
            "id": "autoHide",
            "type": "boolean",
            "default": false
        }
    ],
    "tags": ["editor", "stage"],
    "enabledByDefault": false
};

export default manifest;
