/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Astra Copilot",
  "description": "为 Scratch 添加 AI 辅助编程功能",
  "tags": ["new"],
  "credits": [
    {
      "name": "NeuronPulse",
      "link": "https://github.com/NeuronPulse"
    }
  ],

  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true
};
export default manifest;
